# The טף at the septennial Torah assembly (BHSA)

## Table of content (ToC)<a class="anchor" id="TOC"></a>
* <a href="#bullet1">1 - Introduction
    * <a href="#bullet1x1">1.1 - General introduction</a>
    * <a href="#bullet1x2">1.2 - Reading guide: keep three evidential layers separate</a>
    * <a href="#bullet1x1">1.1 - Working hypotheses</a>
* <a href="#bullet2">2 - Two types of access: direct corpus access and MCP-mediated access</a>
    * <a href="#bullet2x1">2.1 - Which access type does this investigation use?</a>
    * <a href="#bullet2x2">2.2 - Do stdio and SSE represent two more datasets?</a>
* <a href="#bullet3">3 - Locate the repo-local environment and corpus</a>
* <a href="#bullet4">4 - Record software and corpus provenance</a>
* <a href="#bullet5">5 - Check that the MCP server is local</a>
* <a href="#bullet6">6 - Direct MCP initialization and tool discovery</a>
* <a href="#bullet7">7 - Let MCP describe the BHSA corpus and relevant features</a>
* <a href="#bullet8">8 - Retrieve the primary passages directly from local BHSA</a>
* <a href="#bullet9">9 - Build Unicode-safe Hebrew search terms</a>
* <a href="#bullet10">10 - Verify the audience formula and pedagogical verb chain</a>
* <a href="#bullet11">11 - Inspect morphology and syntax, not only strings</a>
    * <a href="#bullet11x1">11.1 - Interpretation of the local syntax</a>
* <a href="#bullet12">12 - Retrieve every `טף` occurrence as a full verse</a>
* <a href="#bullet13">13 - Classify the contexts</a>
    * <a href="#bullet13x1">13.1 - What the distribution does—and does not—show</a>
* <a href="#bullet14">14 - Test the association with women and resident aliens</a>
    * <a href="#bullet14x1">14.1 - The distinctive covenant triad</a>
* <a href="#bullet15">15 - Quantify syntactic roles across all occurrences</a>
* <a href="#bullet16">16 - Historical-critical synthesis</a>
    * <a href="#bullet16x1">16.1 - Lexical result: dependent collective, not an exact age bracket</a>
    * <a href="#bullet16x2">16.2 - Rhetorical result: `כל־העם` is unpacked</a>
    * <a href="#bullet16x3">16.3 - Pedagogical result: hearing precedes durable obedience</a>
    * <a href="#bullet16x4">16.4 - Literary result: Deuteronomy 29 → Deuteronomy 31 → Joshua 8</a>
    * <a href="#bullet16x5">16.5 - Social-historical result: a counterfactual public</a>
    * <a href="#bullet16x6">16.6 - Compositional and institutional questions</a>
    * <a href="#bullet16x7">16.7 - Why Sukkot after the sabbatical year?</a>
* <a href="#bullet17">17 - Conclusions</a>
    * <a href="#bullet17x1">17.1 - Compact answer to the research question</a>
* <a href="#bullet18">18 - Limitations and next investigations</a>
    * <a href="#bullet18x1">18.1 - Limitations</a>
    * <a href="#bullet18x2">18.2 - Strong next steps</a>
* <a href="#bullet19">19 - Data used</a>
* <a href="#bullet20">20 - Final check</a>
* <a href="#bullet21">21 - Required libraries</a>
* <a href="#bullet22">22 - Notebook details</a>

# 1 - Introduction<a class="anchor" id="bullet1"></a>
##### [Back to ToC](#TOC)

## 1.1 - General introduction<a class="anchor" id="bullet1x1"></a>

This Jupyter Notebook investigates a seemingly simple question: why does Deuteronomy 31:12 explicitly include `הטף` — often translated as “the little ones” or “the children” — among those summoned to hear the Torah at Sukkot in every seventh year?

The starting point is the plain text of Deuteronomy 31:10–13. The passage gathers “the people: the men, the women, the `טף`, and your resident alien who is within your gates,” so that they may hear, learn, fear YHWH, and observe the Torah. Verse 13 then turns separately to children “who have not known.” That wording invites lexical, literary, and historical questions which should not be collapsed into one another.

All corpus retrieval in this notebook goes through a *local Context Fabric MCP server* and the local ETCBC BHSA 2021 Text-Fabric files (created by notebook [`shebanq_public_queries.ipynb`](../SHEBANQ-BHSA/shebanq_public_queries.ipynb)).

## 1.2 - Reading guide: keep three evidential layers separate<a class="anchor" id="bullet1"></a>
##### [Back to ToC](#TOC)

A digital corpus can answer some questions with precision and cannot answer others by itself. This notebook therefore marks three layers:

1. **Corpus observation** — what BHSA encodes: words, lexemes, morphology, syntax, references, and distributions.
2. **Literary observation** — how Deuteronomy 31:10–13 relates to nearby Deuteronomic formulas and to Joshua 8:35.
3. **Historical inference** — what these patterns may suggest about scribal ideology, covenant renewal, collective identity, pedagogy, and redaction.

The first layer is reproducible by query. The second depends on close reading. The third is probabilistic.


## 1.3 - Working hypotheses<a class="anchor" id="bullet1x3"></a>
##### [Back to ToC](#TOC)

- `טף` is a collective social category, not a technical label for one exact age.
- Across the Hebrew Bible it frequently denotes dependents or noncombatants in household movement, war, capture, provision, and danger.
- Its inclusion in Deuteronomy 31:12 transfers that vulnerable/dependent category into the covenant assembly, making “all the people” concrete rather than just rhetorical.
- Deuteronomy 29:10, Deuteronomy 31:12, and Joshua 8:35 form a particularly important inclusion formula because `טף` and `גר` occur together only in these three verses.
- The passage is best read as a program of intergenerational covenant reproduction. Whether it describes a regularly performed pre-exilic institution is a separate and much harder historical question.

# 2 - Two types of access: direct corpus access and MCP-mediated access<a class="anchor" id="bullet2"></a>
##### [Back to ToC](#TOC)


The phrase “accessing BHSA” can describe at least two technically different routes. They consult the *same dataset*, but the route from research code to corpus differs. The following table compares a direct  and the MCP mediated access method.

| Question | Direct library/file access | MCP-mediated access |
|---|---|---|
| Who opens BHSA? | The notebook's Python process opens the local Text-Fabric files through Text-Fabric, a file format specific Python library. | The local Context Fabric MCP server opens the local Text-Fabric files. |
| How are requests expressed? | Python method calls tied to the [Text-Fabric API](https://annotation.github.io/text-fabric/tf/). | Standardized [MCP tool calls](https://context-fabric.ai/docs/mcp/guides/tools) such as `describe_corpus`, `search`, and `get_node_features`. |
| Where does corpus state live? | Inside the notebook kernel. | Inside the separately running local MCP server. |
| Main strength | Maximum flexibility for custom, low-level corpus programming. | Tool discovery, explicit schemas, client/language independence, and a clean separation between corpus service and analysis. |
| Main trade-off | Research code is closely coupled to the Text-fabric API and loads the corpus itself. | Queries must fit the tools and schemas exposed by the server; a server process must be running. |


## 2.1 - Which access type does this investigation use?<a class="anchor" id="bullet2x1"></a>
##### [Back to ToC](#TOC)

All textual retrieval, feature inspection, concordance searching, passage retrieval, and syntactic analysis in this notebook will use the MCP-mediated access. The main reason is not technical, but methodical: all textual domains consulted in this investigation will use MCP-mediated access.

The notebook talks to a Context Fabric MCP server running on this same computer, and that server consults only the local ETCBC BHSA 2021 files.

The notebook touches the filesystem directly only for setup and provenance checks: confirming that `otype.tf` and `oslots.tf` exist, counting feature files, locating the server executable, and recording the BHSA Git commit. It does not parse the biblical text or calculate the reported linguistic results directly from `.tf` files.


## 2.2 - Do stdio and SSE represent two more datasets?<a class="anchor" id="bullet2x2"></a>
##### [Back to ToC](#TOC)

No. They are two ways to transport MCP messages:

- stdio transport: the client launches `cfabric-mcp` as a child process and communicates over standard input/output. It needs no listening port and is convenient for a single desktop client.

- local network transport: the server runs independently and listens on a loopback port. Context Fabric supports SSE and streamable HTTP variants. This is convenient for a notebook because the server can stay loaded while many cells open sessions.

This notebook uses local SSE at `http://127.0.0.1:8765/sse`. The endpoint is bound to loopback, so it is not a hosted service. Switching from SSE to stdio or streamable HTTP would change the connection mechanism, not the corpus: the dataset would still be BHSA 2021.

```text
Direct access                         Access used in this notebook

notebook                             notebook
   │ Python corpus API                  │ MCP tool calls over local SSE
   ▼                                    ▼
local BHSA files                     local Context Fabric MCP server
                                           │ Context Fabric corpus access
                                           ▼
                                       local BHSA files
```

# 3 - Locate the repo-local environment and corpus<a class="anchor" id="bullet3"></a>
##### [Back to ToC](#TOC)

Before we can do anything with the corpus, we first will check that:

- the notebook is inside the requested `context_fabric` directory;
- `cfabric-mcp` is installed in the repository-local virtual environment;
- the official BHSA checkout contains the 2021 Text-Fabric warp files;
- all output paths remain local to this repository.

These checks reamin visible because this investigation is meant to remain entirely local. Note that many local files will be excluded from upload to the Github repository (see [.gitignore](.gitignore) in this directory).

In [1]:
# Locate the repo-local environment and corpus
from __future__ import annotations

import asyncio
import hashlib
import importlib.metadata
import json
import os
import re
import shutil
import socket
import subprocess
import sys
import time
import unicodedata
from pathlib import Path
from typing import Any

import pandas as pd
from IPython.display import Markdown, display

pd.set_option("display.max_rows", 100)
pd.set_option("display.max_colwidth", 140)
pd.set_option("display.width", 220)


# Locate the repository root
def find_repo_root(start: Path) -> Path:
    start = start.resolve()
    for candidate in (start, *start.parents):
        if (candidate / ".git").exists():
            return candidate
    raise RuntimeError("Could not locate the repository root from the notebook working directory.")


REPO_ROOT = find_repo_root(Path.cwd())
CONTEXT_DIR = REPO_ROOT / "context_fabric"
CONTEXT_MAPPING_FILE = CONTEXT_DIR / "context_classification_mapping.json"
VENV_DIR = REPO_ROOT / ".context-fabric-venv"
VENV_PYTHON = VENV_DIR / "Scripts" / "python.exe"
BHSA_REPO = CONTEXT_DIR / "data" / "bhsa"
CORPUS_DIR = BHSA_REPO / "tf" / "2021"
RESULTS_DIR = CONTEXT_DIR / "results"
SERVER_DIR = CONTEXT_DIR / "server"
RESULTS_DIR.mkdir(exist_ok=True)
SERVER_DIR.mkdir(exist_ok=True)

MCP_HOST = "127.0.0.1"
MCP_PORT = 8765
MCP_SSE_URL = f"http://{MCP_HOST}:{MCP_PORT}/sse"

required_paths = [CONTEXT_DIR, CONTEXT_MAPPING_FILE, VENV_PYTHON, CORPUS_DIR / "otype.tf", CORPUS_DIR / "oslots.tf"]
missing = [str(path) for path in required_paths if not path.exists()]
if missing:
    raise FileNotFoundError(
        "The local Context Fabric/BHSA setup is incomplete. Missing:\n- " + "\n- ".join(missing)
    )

print("Repository:", REPO_ROOT.name)
print("Context directory:", CONTEXT_DIR.relative_to(REPO_ROOT).as_posix())
print("Local MCP Python:", VENV_PYTHON.relative_to(REPO_ROOT).as_posix())
print("Local BHSA corpus:", CORPUS_DIR.relative_to(REPO_ROOT).as_posix())
print("Local MCP endpoint:", MCP_SSE_URL)

FileNotFoundError: The local Context Fabric/BHSA setup is incomplete. Missing:
- D:\Onedrive\GitHub\Hakhel\.context-fabric-venv\Scripts\python.exe

# 4 - Record software and corpus provenance<a class="anchor" id="bullet4"></a>
##### [Back to ToC](#TOC)

Reproducible corpus work needs more than a book/chapter/verse citation. We record:

- Python and package versions;
- the BHSA Git commit;
- the immutable BHSA version directory (`tf/2021`);
- the number and total size of local `.tf` feature files.

BHSA is the *Biblia Hebraica Stuttgartensia (Amstelodamensis)* dataset prepared by the Eep Talstra Centre for Bible and Computer. Its linguistic annotations are scholarly analyses, not raw facts; this matters especially when we later use the supplied English gloss and syntactic functions.

In [2]:
# Record software and corpus provenance
packages = ["cfabric-mcp", "context-fabric", "mcp", "pandas", "nbformat", "nbclient", "ipykernel"]
package_versions = {
    name: importlib.metadata.version(name)
    for name in packages
}

git_exe = shutil.which("git")
if git_exe is None:
    local_app_data = os.getenv("LOCALAPPDATA")
    github_desktop_root = (
        Path(local_app_data) / "GitHubDesktop"
        if local_app_data
        else None
    )
    candidates = (
        sorted(
            github_desktop_root.glob("app-*/resources/app/git/cmd/git.exe"),
            reverse=True,
        )
        if github_desktop_root and github_desktop_root.exists()
        else []
    )
    if candidates:
        git_exe = str(candidates[0])
if git_exe is None:
    raise FileNotFoundError("Git is required to record the local BHSA commit.")

bhsa_commit = subprocess.run(
    [git_exe, "rev-parse", "HEAD"],
    cwd=BHSA_REPO,
    check=True,
    capture_output=True,
    text=True,
).stdout.strip()

tf_files = list(CORPUS_DIR.glob("*.tf"))
context_mapping_sha256 = hashlib.sha256(CONTEXT_MAPPING_FILE.read_bytes()).hexdigest()

provenance = {
    "python": sys.version.split()[0],
    "packages": package_versions,
    "bhsa_commit": bhsa_commit,
    "bhsa_version_directory": "tf/2021",
    "tf_feature_file_count": len(tf_files),
    "tf_feature_bytes": sum(path.stat().st_size for path in tf_files),
    "mcp_url": MCP_SSE_URL,
    "researcher_supplied_mappings": {
        "context_frame": {
            "file": CONTEXT_MAPPING_FILE.relative_to(REPO_ROOT).as_posix(),
            "sha256": context_mapping_sha256,
            "claim": "Explicit interpretive coding, not a BHSA or Context Fabric feature.",
        }
    },
}
display(pd.Series(provenance, name="value").to_frame())

(RESULTS_DIR / "provenance.json").write_text(
    json.dumps(provenance, ensure_ascii=False, indent=2) + "\n",
    encoding="utf-8",
)

                                                                                                                                                                    value
python                                                                                                                                                            3.13.14
packages                      {'cfabric-mcp': '0.1.7', 'context-fabric': '0.5.7', 'mcp': '1.28.1', 'pandas': '3.0.3', 'nbformat': '5.10.4', 'nbclient': '0.11.0', 'ipy...
bhsa_commit                                                                                                                      4db00e2157915495e1a4d3d57e41223df24775da
bhsa_version_directory                                                                                                                                            tf/2021
tf_feature_file_count                                                                                                                                                 117
tf_feature_bytes                                                                                                                                                208996790
mcp_url                                                                                                                                         http://127.0.0.1:8765/sse
researcher_supplied_mappings  {'context_frame': {'file': 'context_fabric/context_classification_mapping.json', 'sha256': '89b8425d65c0376095a19dcc6bfcbc688ffb02117716...

741

# 5 - Check that the MCP server is local<a class="anchor" id="bullet5"></a>
##### [Back to ToC](#TOC)

The notebook first probes `127.0.0.1:8765`. If no process is listening, it launches the repo-local `cfabric-mcp.exe` with the repo-local BHSA path.

The feature list is broad enough for this study: references, Hebrew forms, lexemes, glosses, morphology, phrase/clause functions and types, discourse domains, and parent relations. Context Fabric compiles a `.cfm` cache beside the corpus on first use. That first compilation is resource-intensive; later launches reuse the cache.

Binding to `127.0.0.1` rather than `0.0.0.0` keeps the research service accessible only from this computer.

Note that the first time this cell is runned, it might take a long time since it needs to download and compile many BHSA related data files.

In [3]:
# Start and verify a genuinely local Context Fabric MCP server

FEATURES = " ".join(
    [
        "book", "chapter", "verse",
        "lex", "lex_utf8", "g_lex_utf8", "g_word_utf8", "g_cons_utf8",
        "voc_lex_utf8", "gloss",
        "sp", "pdp", "gn", "nu", "ps", "st", "vt", "vs", "ls",
        "language", "function", "typ", "domain", "kind", "rela",
        "mother", "mother_object_type", "label", "trailer_utf8", "freq_lex",
    ]
)


def port_is_open(host: str, port: int, timeout: float = 0.5) -> bool:
    """Return True when a TCP connection can be made to host:port."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.settimeout(timeout)
        return sock.connect_ex((host, port)) == 0


def read_log(path: Path) -> str:
    """Read a log file without failing on encoding problems."""
    if not path.exists():
        return "[log file not created]"

    content = path.read_text(
        encoding="utf-8",
        errors="replace",
    )

    return content if content else "[empty]"


SERVER_DIR.mkdir(parents=True, exist_ok=True)

stdout_path = SERVER_DIR / "cfabric-mcp.stdout.log"
stderr_path = SERVER_DIR / "cfabric-mcp.stderr.log"
pid_path = SERVER_DIR / "cfabric-mcp.pid"

# Run the server with the repository-local Python environment.
venv_python = VENV_PYTHON

if not venv_python.is_file():
    raise RuntimeError(
        "The repository-local Python interpreter was not found:\n"
        f"{venv_python}\n\n"
    )

if not CORPUS_DIR.is_dir():
    raise RuntimeError(
        "The Context Fabric corpus directory was not found:\n"
        f"{CORPUS_DIR}"
    )


# Verify that both distributions are installed in the MCP environment.
package_probe_code = """
from importlib.metadata import version

for package in ("cfabric-mcp", "context-fabric"):
    print(f"{package}={version(package)}")
"""

package_probe = subprocess.run(
    [
        str(venv_python),
        "-c",
        package_probe_code,
    ],
    capture_output=True,
    text=True,
    encoding="utf-8",
    errors="replace",
)

if package_probe.returncode != 0:
    repair_command = subprocess.list2cmdline(
        [
            str(venv_python),
            "-m",
            "pip",
            "install",
            "-r",
            str(CONTEXT_DIR / "requirements.txt"),
        ]
    )

    raise RuntimeError(
        "The dedicated MCP environment could not load its packages.\n\n"
        f"Python: {venv_python}\n"
        f"Exit code: {package_probe.returncode}\n\n"
        f"STDOUT:\n{package_probe.stdout or '[empty]'}\n\n"
        f"STDERR:\n{package_probe.stderr or '[empty]'}\n\n"
        "Repair the environment by running:\n"
        f"{repair_command}"
    )

print("Dedicated MCP environment:")
print(package_probe.stdout.strip())


# Load the cfabric-mcp console entry point through the virtual environment's
# Python interpreter. This bypasses a potentially stale Windows .exe launcher.
console_entry_code = """
from importlib.metadata import distribution

entry_point = next(
    ep
    for ep in distribution("cfabric-mcp").entry_points
    if ep.group == "console_scripts" and ep.name == "cfabric-mcp"
)

raise SystemExit(entry_point.load()())
"""


server_started_by_notebook = False
server_process = None

if port_is_open(MCP_HOST, MCP_PORT):
    print(
        f"A service is already listening on "
        f"{MCP_HOST}:{MCP_PORT}; no new server was started."
    )

else:
    server_command = [
        str(venv_python),
        "-c",
        console_entry_code,
        "--corpus", f"bhsa={CORPUS_DIR}",
        "--features", FEATURES,
        "--sse", str(MCP_PORT),
        "--host", MCP_HOST,
        "--verbose",
    ]

    # Clear logs from previous runs.
    stdout_path.write_text("", encoding="utf-8")
    stderr_path.write_text("", encoding="utf-8")

    stdout_handle = stdout_path.open("w", encoding="utf-8")
    stderr_handle = stderr_path.open("w", encoding="utf-8")

    creationflags = getattr(subprocess, "CREATE_NO_WINDOW", 0)

    try:
        server_process = subprocess.Popen(
            server_command,
            cwd=str(CORPUS_DIR),
            stdout=stdout_handle,
            stderr=stderr_handle,
            creationflags=creationflags,
        )
    finally:
        # The child process retains its own log handles.
        stdout_handle.close()
        stderr_handle.close()

    pid_path.write_text(
        str(server_process.pid),
        encoding="ascii",
    )

    server_started_by_notebook = True
    startup_timeout_seconds = 120
    deadline = time.time() + startup_timeout_seconds

    while time.time() < deadline:
        if port_is_open(MCP_HOST, MCP_PORT):
            break

        return_code = server_process.poll()

        if return_code is not None:
            raise RuntimeError(
                "Local Context Fabric MCP exited during startup.\n\n"
                f"Exit code: {return_code}\n"
                f"Python: {venv_python}\n"
                f"Corpus: {CORPUS_DIR}\n"
                f"Host: {MCP_HOST}\n"
                f"Port: {MCP_PORT}\n\n"
                f"STDOUT:\n{read_log(stdout_path)}\n\n"
                f"STDERR:\n{read_log(stderr_path)}"
            )

        time.sleep(2)

    if not port_is_open(MCP_HOST, MCP_PORT):
        # Stop only the process started by this notebook cell.
        if server_process.poll() is None:
            server_process.terminate()

            try:
                server_process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                server_process.kill()
                server_process.wait(timeout=10)

        raise RuntimeError(
            "Local Context Fabric MCP did not open its port within "
            f"{startup_timeout_seconds} seconds.\n\n"
            f"Process exit code: {server_process.returncode}\n"
            f"Python: {venv_python}\n"
            f"Corpus: {CORPUS_DIR}\n"
            f"Host: {MCP_HOST}\n"
            f"Port: {MCP_PORT}\n\n"
            f"STDOUT:\n{read_log(stdout_path)}\n\n"
            f"STDERR:\n{read_log(stderr_path)}"
        )

    print(
        f"Started local Context Fabric MCP at "
        f"http://{MCP_HOST}:{MCP_PORT}/sse "
        f"(PID {server_process.pid})."
    )

Dedicated MCP environment:
cfabric-mcp=0.1.7
context-fabric=0.5.7

Started local Context Fabric MCP at http://127.0.0.1:8765/sse (PID 38860).

# 6 - Direct MCP initialization and tool discovery<a class="anchor" id="bullet6"></a>
##### [Back to ToC](#TOC)

This is the investigation's first corpus interaction. We do not assume tool names copied from documentation. We initialize an MCP session and ask the running local server to describe itself and list its callable tools with JSON schemas.

This avoids a surprisingly easy reproducibility error: writing code for an imagined `bhsa_search` tool when the actual server exposes `search`, `get_passages`, `get_node_features`, and discovery tools.

In [4]:
# Direct MCP initialization and tool discovery
from mcp import ClientSession
from mcp.client.sse import sse_client


# Decode MCP content blocks
def decode_mcp_result(result: Any) -> Any:
    decoded = []
    for item in result.content:
        text = getattr(item, "text", str(item))
        try:
            decoded.append(json.loads(text))
        except json.JSONDecodeError:
            decoded.append(text)
    return decoded[0] if len(decoded) == 1 else decoded


# Call one MCP tool
async def mcp_call(tool_name: str, arguments: dict[str, Any] | None = None) -> Any:
    async with sse_client(MCP_SSE_URL) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            result = await session.call_tool(tool_name, arguments or {})
            return decode_mcp_result(result)


# Read the local server description
async def discover_local_server() -> dict[str, Any]:
    async with sse_client(MCP_SSE_URL) as (read, write):
        async with ClientSession(read, write) as session:
            initialized = await session.initialize()
            listed = await session.list_tools()
            return {
                "server": initialized.serverInfo.model_dump(),
                "protocol_version": initialized.protocolVersion,
                "tools": [tool.model_dump() for tool in listed.tools],
            }


discovery = await discover_local_server()
tool_catalog = pd.DataFrame(
    [
        {
            "tool": tool["name"],
            "description": tool.get("description", "").splitlines()[0],
            "required_arguments": tool.get("inputSchema", {}).get("required", []),
        }
        for tool in discovery["tools"]
    ]
)
display(pd.Series(discovery["server"], name="server value").to_frame())
display(tool_catalog)

(RESULTS_DIR / "mcp_tool_inventory.json").write_text(
    json.dumps(discovery, ensure_ascii=False, indent=2) + "\n",
    encoding="utf-8",
)

              server value
name        Context-Fabric
title                  NaN
version             1.28.1
websiteUrl             NaN
icons                  NaN

                   tool                                                             description     required_arguments
0          list_corpora                                      List all currently loaded corpora.                     []
1       describe_corpus                                          Get corpus structure overview.                     []
2      describe_feature                           Get detailed info about one or more features.              [feature]
3         list_features                                  List features with optional filtering.                     []
4      get_text_formats  Get text encoding samples showing original script and transliteration.                     []
5                search                                      Search for patterns in the corpus.             [template]
6       search_continue                          Continue a paginated search using a cursor ID.            [cursor_id]
7            search_csv                                    Export search results to a CSV file.  [template, file_path]
8   search_syntax_guide                            Get documentation on search template syntax.                     []
9          get_passages                                     Get passages by section references.             [sections]
10    get_node_features                                 Get feature values for a list of nodes.      [nodes, features]

17473

# 7 - Let MCP describe the BHSA corpus and relevant features<a class="anchor" id="bullet7"></a>
##### [Back to ToC](#TOC)

Before searching, we ask the server:

- which corpus is loaded;
- which node types and section levels exist;
- what `lex_utf8`, `g_word_utf8`, `gloss`, `sp`, `function`, `typ`, and `domain` mean in this dataset;
- what search syntax this server accepts.

This step helps us avoid mixing conventions. For example, BHSA stores Deuteronomy's `book` feature as `Deuteronomium`, although MCP renders human-facing references as `Deuteronomy`.

In [5]:
# Let MCP describe the BHSA corpus and relevant features
corpora_info = await mcp_call("list_corpora")
corpus_description = await mcp_call("describe_corpus", {"corpus": "bhsa"})
feature_description = await mcp_call(
    "describe_feature",
    {
        "corpus": "bhsa",
        "feature": [
            "book", "chapter", "verse", "lex_utf8", "g_word_utf8",
            "gloss", "sp", "function", "typ", "domain",
        ],
        "sample_limit": 12,
    },
)
search_guide = await mcp_call("search_syntax_guide")

display(pd.Series(corpora_info, name="value").to_frame())
display(pd.DataFrame(corpus_description["node_types"]))

feature_rows = []
for name, details in feature_description["features"].items():
    feature_rows.append(
        {
            "feature": name,
            "kind": details["kind"],
            "value_type": details["value_type"],
            "node_types": ", ".join(details["node_types"]),
            "description": details["description"],
            "unique_values": details["unique_values"],
        }
    )
display(pd.DataFrame(feature_rows))
display(pd.Series(search_guide, name="value").to_frame())

          value
corpora  [bhsa]
current    bhsa

             type   count  is_slot_type
0            book      39         False
1         chapter     929         False
2             lex    9230         False
3           verse   23213         False
4      half_verse   45179         False
5        sentence   63717         False
6   sentence_atom   64514         False
7          clause   88131         False
8     clause_atom   90704         False
9          phrase  253203         False
10    phrase_atom  267532         False
11      subphrase  113850         False
12           word  426590          True

       feature  kind value_type                                node_types                                                                         description  unique_values
0         book  node        str                      book, chapter, verse                                 ✅ book name in Latin (Genesis; Numeri; Reges1; ...)             39
1      chapter  node        int                            chapter, verse                                                     ✅ chapter number (1; 2; 3; ...)            150
2        verse  node        int                                     verse                                                                      ✅ verse number            176
3     lex_utf8  node        str                                 lex, word                                  ✅ lexeme consonantal-Hebrew (ב ראשׁית֜ ברא אלהים֜)          12132
4  g_word_utf8  node        str                                      word                             ✅ word pointed-Hebrew (בְּ רֵאשִׁ֖ית בָּרָ֣א אֱלֹהִ֑ים)          92474
5        gloss  node        str                                 lex, word                           🆗 english translation of lexeme (beginning create god(s))           6132
6           sp  node        str                                 lex, word                                       ✅ part-of-speech (art; verb; subs; nmpr, ...)             14
7     function  node        str                                    phrase                              ✅ syntactic function of phrase (Cmpl; Objc; Pred; ...)             29
8          typ  node        str  clause, clause_atom, phrase, phrase_atom                               ✅ clause/phrase(atom) type (VP; NP; Ellp; Ptcp; WayX)             56
9       domain  node        str                                    clause  ✅ text type of clause (? (Unknown); N (narrative); D (discursive); Q (Quotation).)              4

                                                                                                    value
summary   Templates: node_type feature=value. Indentation=containment. Relations: < > <: >: for ordering.
sections                                            [basics, structure, relations, quantifiers, examples]
hint                             Call with section='relations' to get detailed info on a specific section

# 8 - Retrieve the primary passages directly from local BHSA<a class="anchor" id="bullet8"></a>
##### [Back to ToC](#TOC)

We begin with Deuteronomy 31:10–13, rather than verse 12 in isolation:

- verse 10 fixes the seventh-year/Sukkot schedule;
- verse 11 commands public Torah reading at the chosen place;
- verse 12 defines the audience and purpose;
- verse 13 explains intergenerational continuation through children “who have not known.”

Two comparison texts are added:

- **Deuteronomy 29:9–11**: covenant standing before YHWH, including `טף`, women, and resident alien;
- **Joshua 8:34–35**: narrative Torah reading before the assembly, including women, `טף`, and resident alien.

Joshua 8:35 is not independent proof that Deuteronomy 31 was historically performed exactly as written. Literarily, however, it is a powerful Deuteronomistic realization of the same totalizing audience ideal.

The installed Context-Fabric MCP version currently returns an internal `Computeds.sections` error from its convenience tool `get_passages`. We therefore retrieve the same verses with exact `search` templates, the same route used for the investigation below. The small name mapping is stated in the code: BHSA stores `Deuteronomium` and `Josua` in its `book` feature, while Context Fabric renders the references in English as `Deuteronomy` and `Joshua`. No verse text is supplied by this notebook.

In [6]:
# Retrieve the selected verses through exact Context-Fabric searches.
# Each tuple records: displayed English book, BHSA book-feature value, chapter, verse.
PRIMARY_SECTIONS = [
    ("Deuteronomy", "Deuteronomium", 29, 9),
    ("Deuteronomy", "Deuteronomium", 29, 10),
    ("Deuteronomy", "Deuteronomium", 29, 11),
    ("Deuteronomy", "Deuteronomium", 31, 10),
    ("Deuteronomy", "Deuteronomium", 31, 11),
    ("Deuteronomy", "Deuteronomium", 31, 12),
    ("Deuteronomy", "Deuteronomium", 31, 13),
    ("Joshua", "Josua", 8, 34),
    ("Joshua", "Josua", 8, 35),
]

primary_rows = []
for display_book, bhsa_book, chapter, verse in PRIMARY_SECTIONS:
    response = await mcp_call(
        "search",
        {
            "corpus": "bhsa",
            "template": f"v:verse book={bhsa_book} chapter={chapter} verse={verse}",
            "return_type": "passages",
            "limit": 2,
        },
    )
    expected_reference = f"{display_book} {chapter}:{verse}"
    assert response["total_count"] == 1, (
        f"Expected one BHSA verse for {expected_reference}; "
        f"Context Fabric returned {response['total_count']}."
    )
    passage = response["passages"][0]
    assert passage["reference"] == expected_reference
    primary_rows.append(
        {
            "section_ref": passage["reference"],
            "node": passage["node"],
            "text": passage["text"],
        }
    )

primary_df = pd.DataFrame(primary_rows)
display(primary_df)

         section_ref     node                                                                                                                                         text
0   Deuteronomy 29:9  1420079  אַתֶּ֨ם נִצָּבִ֤ים הַיֹּום֙ כֻּלְּכֶ֔ם לִפְנֵ֖י יְהוָ֣ה אֱלֹהֵיכֶ֑ם רָאשֵׁיכֶ֣ם שִׁבְטֵיכֶ֗ם זִקְנֵיכֶם֙ וְשֹׁ֣טְרֵיכֶ֔ם כֹּ֖ל אִ֥ישׁ יִ...
1  Deuteronomy 29:10  1420080                                      טַפְּכֶ֣ם נְשֵׁיכֶ֔ם וְגֵ֣רְךָ֔ אֲשֶׁ֖ר בְּקֶ֣רֶב מַחֲנֶ֑יךָ מֵחֹטֵ֣ב עֵצֶ֔יךָ עַ֖ד שֹׁאֵ֥ב מֵימֶֽיךָ׃
2  Deuteronomy 29:11  1420081                                לְעָבְרְךָ֗ בִּבְרִ֛ית יְהוָ֥ה אֱלֹהֶ֖יךָ וּבְאָלָתֹ֑ו אֲשֶׁר֙ יְהוָ֣ה אֱלֹהֶ֔יךָ כֹּרֵ֥ת עִמְּךָ֖ הַיֹּֽום׃
3  Deuteronomy 31:10  1420128                             וַיְצַ֥ו מֹשֶׁ֖ה אֹותָ֣ם לֵאמֹ֑ר מִקֵּ֣ץ׀ שֶׁ֣בַע שָׁנִ֗ים בְּמֹעֵ֛ד שְׁנַ֥ת הַשְּׁמִטָּ֖ה בְּחַ֥ג הַסֻּכֹּֽות׃
4  Deuteronomy 31:11  1420129  בְּבֹ֣וא כָל־יִשְׂרָאֵ֗ל לֵרָאֹות֙ אֶת־פְּנֵי֙ יְהוָ֣ה אֱלֹהֶ֔יךָ בַּמָּקֹ֖ום אֲשֶׁ֣ר יִבְחָ֑ר תִּקְרָ֞א אֶת־הַתֹּורָ֥ה הַזֹּ֛את נֶ֥גֶד ...
5  Deuteronomy 31:12  1420130  הַקְהֵ֣ל אֶת־הָעָ֗ם הָֽאֲנָשִׁ֤ים וְהַנָּשִׁים֙ וְהַטַּ֔ף וְגֵרְךָ֖ אֲשֶׁ֣ר בִּשְׁעָרֶ֑יךָ לְמַ֨עַן יִשְׁמְע֜וּ וּלְמַ֣עַן יִלְמְד֗וּ וְ...
6  Deuteronomy 31:13  1420131  וּבְנֵיהֶ֞ם אֲשֶׁ֣ר לֹֽא־יָדְע֗וּ יִשְׁמְעוּ֙ וְלָ֣מְד֔וּ לְיִרְאָ֖ה אֶת־יְהוָ֣ה אֱלֹהֵיכֶ֑ם כָּל־הַיָּמִ֗ים אֲשֶׁ֨ר אַתֶּ֤ם חַיִּים֙ עַ...
7        Joshua 8:34  1420426                      וְאַֽחֲרֵי־כֵ֗ן קָרָא֙ אֶת־כָּל־דִּבְרֵ֣י הַתֹּורָ֔ה הַבְּרָכָ֖ה וְהַקְּלָלָ֑ה כְּכָל־הַכָּת֖וּב בְּסֵ֥פֶר הַתֹּורָֽה׃
8        Joshua 8:35  1420427  לֹֽא־הָיָ֣ה דָבָ֔ר מִכֹּ֖ל אֲשֶׁר־צִוָּ֣ה מֹשֶׁ֑ה אֲשֶׁ֨ר לֹֽא־קָרָ֜א יְהֹושֻׁ֗עַ נֶ֣גֶד כָּל־קְהַ֤ל יִשְׂרָאֵל֙ וְהַנָּשִׁ֣ים וְהַטַּ֔ף...

# 9 - Build Unicode-safe Hebrew search terms<a class="anchor" id="bullet9"></a>
##### [Back to ToC](#TOC)

On Windows PowerShell 5, literal Hebrew piped into a Python process may be converted to question marks before MCP receives it. A notebook normally stores Unicode safely, but explicit code-point construction keeps the query safe across the different environments used here.

Important BHSA lexemes:

- `טף` — collective dependents / little ones;
- `אישׁ`, `אשׁה`, `גר` — man, woman, resident alien/sojourner;
- `שׁמע`, `למד`, `ירא`, `שׁמר`, `עשׂה` — hear, learn, fear, keep, do;
- `בן`, `ידע` — child/son and know in verse 13.

In [7]:
# Build Unicode-safe Hebrew search terms
H = {
    "taf": "\u05d8\u05e3",
    "man": "\u05d0\u05d9\u05e9\u05c1",
    "woman": "\u05d0\u05e9\u05c1\u05d4",
    "ger": "\u05d2\u05e8",
    "hear": "\u05e9\u05c1\u05de\u05e2",
    "learn": "\u05dc\u05de\u05d3",
    "fear": "\u05d9\u05e8\u05d0",
    "keep": "\u05e9\u05c1\u05de\u05e8",
    "do": "\u05e2\u05e9\u05c2\u05d4",
    "son": "\u05d1\u05df",
    "know": "\u05d9\u05d3\u05e2",
}
pd.Series(H, name="BHSA lex_utf8").to_frame()

      BHSA lex_utf8
taf              טף
man            אישׁ
woman          אשׁה
ger              גר
hear           שׁמע
learn           למד
fear            ירא
keep           שׁמר
do             עשׂה
son              בן
know            ידע

# 10 - Verify the audience formula and pedagogical verb chain<a class="anchor" id="bullet10"></a>
##### [Back to ToC](#TOC)

The search captures the verse plus each relevant word. Same-level query lines follow canonical order in Context Fabric's template language.

Two grammatical observations matter:

1. The audience categories occur inside the object of the singular imperative “assemble.”
2. The subsequent verbs are third-person plural: “they may hear … learn … fear … keep … do.” At the grammatical level, the stated purpose belongs to the assembled collective. The text does not mark `טף` as a parenthetical group exempt from the purpose chain.

Verse 13 then narrows attention to descendants “who have not known,” supplying an explicit intergenerational rationale without defining a minimum age.

In [8]:
# Verify the audience formula and pedagogical verb chain
audience_template = f'''verse book=Deuteronomium chapter=31 verse=12
  m:word lex_utf8={H['man']}
  w:word lex_utf8={H['woman']}
  t:word lex_utf8={H['taf']}
  g:word lex_utf8={H['ger']}'''

purpose_template = f'''verse book=Deuteronomium chapter=31 verse=12
  h:word lex_utf8={H['hear']}
  l:word lex_utf8={H['learn']}
  f:word lex_utf8={H['fear']}
  k:word lex_utf8={H['keep']}
  d:word lex_utf8={H['do']}'''

verse13_template = f'''verse book=Deuteronomium chapter=31 verse=13
  b:word lex_utf8={H['son']}
  k:word lex_utf8={H['know']}
  h:word lex_utf8={H['hear']}
  l:word lex_utf8={H['learn']}
  f:word lex_utf8={H['fear']}'''

audience_result = await mcp_call(
    "search", {"template": audience_template, "return_type": "results", "limit": 20, "corpus": "bhsa"}
)
purpose_result = await mcp_call(
    "search", {"template": purpose_template, "return_type": "results", "limit": 20, "corpus": "bhsa"}
)
verse13_result = await mcp_call(
    "search", {"template": verse13_template, "return_type": "results", "limit": 20, "corpus": "bhsa"}
)


# Collect the named nodes from the first match
def captured_nodes(result: dict[str, Any]) -> pd.DataFrame:
    return pd.DataFrame(result["results"][0])


display(Markdown("### Deuteronomy 31:12 audience"))
display(captured_nodes(audience_result))
display(Markdown("### Deuteronomy 31:12 purpose chain"))
display(captured_nodes(purpose_result))
display(Markdown("### Deuteronomy 31:13 intergenerational chain"))
display(captured_nodes(verse13_result))

### Deuteronomy 31:12 audience

      node  otype                                                                                                                                         text        section_ref
0  1420130  verse  הַקְהֵ֣ל אֶת־הָעָ֗ם הָֽאֲנָשִׁ֤ים וְהַנָּשִׁים֙ וְהַטַּ֔ף וְגֵרְךָ֖ אֲשֶׁ֣ר בִּשְׁעָרֶ֑יךָ לְמַ֨עַן יִשְׁמְע֜וּ וּלְמַ֣עַן יִלְמְד֗וּ וְ...  Deuteronomy 31:12
1   110925   word                                                                                                                                  אֲנָשִׁ֤ים   Deuteronomy 31:12
2   110928   word                                                                                                                                   נָּשִׁים֙   Deuteronomy 31:12
3   110931   word                                                                                                                                       טַּ֔ף   Deuteronomy 31:12
4   110933   word                                                                                                                                     גֵרְךָ֖   Deuteronomy 31:12

### Deuteronomy 31:12 purpose chain

      node  otype                                                                                                                                         text        section_ref
0  1420130  verse  הַקְהֵ֣ל אֶת־הָעָ֗ם הָֽאֲנָשִׁ֤ים וְהַנָּשִׁים֙ וְהַטַּ֔ף וְגֵרְךָ֖ אֲשֶׁ֣ר בִּשְׁעָרֶ֑יךָ לְמַ֨עַן יִשְׁמְע֜וּ וּלְמַ֣עַן יִלְמְד֗וּ וְ...  Deuteronomy 31:12
1   110938   word                                                                                                                                 יִשְׁמְע֜וּ   Deuteronomy 31:12
2   110941   word                                                                                                                                  יִלְמְד֗וּ   Deuteronomy 31:12
3   110943   word                                                                                                                                   יָֽרְאוּ֙   Deuteronomy 31:12
4   110948   word                                                                                                                                  שָֽׁמְר֣וּ   Deuteronomy 31:12
5   110950   word                                                                                                                                    עֲשֹׂ֔ות   Deuteronomy 31:12

### Deuteronomy 31:13 intergenerational chain

      node  otype                                                                                                                                         text        section_ref
0  1420131  verse  וּבְנֵיהֶ֞ם אֲשֶׁ֣ר לֹֽא־יָדְע֗וּ יִשְׁמְעוּ֙ וְלָ֣מְד֔וּ לְיִרְאָ֖ה אֶת־יְהוָ֣ה אֱלֹהֵיכֶ֑ם כָּל־הַיָּמִ֗ים אֲשֶׁ֨ר אַתֶּ֤ם חַיִּים֙ עַ...  Deuteronomy 31:13
1   110959   word                                                                                                                                   בְנֵיהֶ֞ם   Deuteronomy 31:13
2   110962   word                                                                                                                                    יָדְע֗וּ   Deuteronomy 31:13
3   110963   word                                                                                                                                 יִשְׁמְעוּ֙   Deuteronomy 31:13
4   110965   word                                                                                                                                   לָ֣מְד֔וּ   Deuteronomy 31:13
5   110967   word                                                                                                                                    יִרְאָ֖ה   Deuteronomy 31:13

# 11 - Inspect morphology and syntax, not only strings<a class="anchor" id="bullet11"></a>
##### [Back to ToC](#TOC)

We now ask MCP for features on the captured word nodes and for the phrase/clause that contain `טף`.

This matters because a translation such as “little ones” may suggest an age-specific plural noun. BHSA instead analyzes `טף` as:

- a substantive;
- masculine singular;
- functioning collectively;
- glossed by the annotators as “those unable to march.”

That gloss should not be treated as inspired lexicography. It is, however, a compact summary of the distributional fact that the term repeatedly contrasts mobile/fighting adults with dependents.

In [9]:
# Inspect morphology and syntax, not only strings
captured_word_nodes = [
    item["node"]
    for payload in (audience_result, purpose_result, verse13_result)
    for item in payload["results"][0]
    if item["otype"] == "word"
]
word_features = await mcp_call(
    "get_node_features",
    {
        "nodes": sorted(set(captured_word_nodes)),
        "features": [
            "lex_utf8", "g_word_utf8", "gloss", "sp", "pdp",
            "gn", "nu", "ps", "st", "vt", "vs", "language",
        ],
        "corpus": "bhsa",
    },
)
word_feature_df = pd.DataFrame(word_features["nodes"])
display(word_feature_df)

deut_structure = await mcp_call(
    "search",
    {
        "template": f'''verse book=Deuteronomium chapter=31 verse=12
  c:clause
    p:phrase
      w:word lex_utf8={H['taf']}''',
        "return_type": "results",
        "limit": 20,
        "corpus": "bhsa",
    },
)
josh_structure = await mcp_call(
    "search",
    {
        "template": f'''verse book=Josua chapter=8 verse=35
  c:clause
    p:phrase
      w:word lex_utf8={H['taf']}''',
        "return_type": "results",
        "limit": 20,
        "corpus": "bhsa",
    },
)

structure_nodes = [
    item["node"]
    for payload in (deut_structure, josh_structure)
    for item in payload["results"][0]
]
structure_features = await mcp_call(
    "get_node_features",
    {
        "nodes": structure_nodes,
        "features": ["function", "typ", "domain", "kind", "rela", "lex_utf8", "g_word_utf8", "gloss"],
        "corpus": "bhsa",
    },
)
structure_df = pd.DataFrame(structure_features["nodes"])
display(structure_df)

      node  type lex_utf8  g_word_utf8                    gloss    sp   pdp       gn       nu       ps  st    vt   vs language
0   110925  word     אישׁ   אֲנָשִׁ֤ים                      man  subs  subs        m       pl       NA   a    NA   NA   Hebrew
1   110928  word     אשׁה    נָּשִׁים֙                    woman  subs  subs        f       pl       NA   a    NA   NA   Hebrew
2   110931  word       טף        טַּ֔ף  <those unable to march>  subs  subs        m       sg       NA   a    NA   NA   Hebrew
3   110933  word       גר      גֵרְךָ֖                sojourner  subs  subs        m       sg       NA   a    NA   NA   Hebrew
4   110938  word     שׁמע  יִשְׁמְע֜וּ                     hear  verb  verb        m       pl       p3  NA  impf  qal   Hebrew
5   110941  word      למד   יִלְמְד֗וּ                    learn  verb  verb        m       pl       p3  NA  impf  qal   Hebrew
6   110943  word      ירא    יָֽרְאוּ֙                     fear  verb  verb  unknown       pl       p3  NA  perf  qal   Hebrew
7   110948  word     שׁמר   שָֽׁמְר֣וּ                     keep  verb  verb  unknown       pl       p3  NA  perf  qal   Hebrew
8   110950  word     עשׂה     עֲשֹׂ֔ות                     make  verb  verb  unknown  unknown  unknown   a  infc  qal   Hebrew
9   110959  word       בן    בְנֵיהֶ֞ם                      son  subs  subs        m       pl       NA   a    NA   NA   Hebrew
10  110962  word      ידע     יָדְע֗וּ                     know  verb  verb  unknown       pl       p3  NA  perf  qal   Hebrew
11  110963  word     שׁמע  יִשְׁמְעוּ֙                     hear  verb  verb        m       pl       p3  NA  impf  qal   Hebrew
12  110965  word      למד    לָ֣מְד֔וּ                    learn  verb  verb  unknown       pl       p3  NA  perf  qal   Hebrew
13  110967  word      ירא     יִרְאָ֖ה                     fear  verb  verb  unknown  unknown  unknown   a  infc  qal   Hebrew

      node    type function   typ domain kind  rela lex_utf8 g_word_utf8                    gloss
0  1420130   verse      NaN   NaN    NaN  NaN   NaN      NaN         NaN                      NaN
1   448290  clause      NaN  ZIm0      Q   VC    NA      NaN         NaN                      NaN
2   714520  phrase     Objc    PP    NaN  NaN    NA      NaN         NaN                      NaN
3   110931    word      NaN   NaN    NaN  NaN   NaN       טף       טַּ֔ף  <those unable to march>
4  1420427   verse      NaN   NaN    NaN  NaN   NaN      NaN         NaN                      NaN
5   449606  clause      NaN  xQtX      N   VC  Attr      NaN         NaN                      NaN
6   718417  phrase     Cmpl    PP    NaN  NaN    NA      NaN         NaN                      NaN
7   117735    word      NaN   NaN    NaN  NaN   NaN       טף       טַּ֔ף  <those unable to march>

## 11.1 - Interpretation of the local syntax<a class="anchor" id="bullet11x1"></a>
##### [Back to ToC](#TOC)

BHSA analyzes the opening command of Deuteronomy 31:12 as a quotation-domain verbal clause (`ZIm0`, an imperative pattern). The entire sequence “the people—the men, the women, the `טף`, and your resident alien” belongs to one object phrase. `טף` is therefore structurally integrated into the commanded assembly.

Joshua 8:35 differs syntactically because it narrates reading “before” the whole assembly; BHSA labels the phrase containing women, `טף`, and resident alien as a complement. The social inclusion formula survives even though the clause's grammatical architecture changes.

This difference is worth noting. Joshua does not mechanically copy a complete Deuteronomic sentence, but reuses the same constituency formula in a new narrative syntax.

# 12 - Retrieve every `טף` occurrence as a full verse<a class="anchor" id="bullet12"></a>
##### [Back to ToC](#TOC)

A lexeme-level study should not infer meaning from a dictionary gloss alone. We search the entire corpus for a verse containing a `טף` word, capture both the verse and the word node, and inspect all 42 contexts.

Using the verse as the query root is important. A query rooted at `word` returns only the matched word as its “passage,” which hides the social frame.

In [10]:
# Retrieve every `טף` occurrence as a full verse
all_taf_template = f'''v:verse
  w:word lex_utf8={H['taf']}'''

all_taf_result = await mcp_call(
    "search",
    {
        "template": all_taf_template,
        "return_type": "results",
        "limit": 100,
        "max_override": True,
        "corpus": "bhsa",
    },
)
assert all_taf_result["total_count"] == 42

occurrence_rows = []
for match in all_taf_result["results"]:
    verse_item = next(item for item in match if item["otype"] == "verse")
    word_item = next(item for item in match if item["otype"] == "word")
    occurrence_rows.append(
        {
            "reference": verse_item["section_ref"],
            "verse_node": verse_item["node"],
            "word_node": word_item["node"],
            "matched_form": word_item["text"].strip(),
            "verse_text": verse_item["text"].strip(),
        }
    )

taf_df = pd.DataFrame(occurrence_rows)
display(taf_df[["reference", "matched_form", "verse_text"]])

             reference matched_form                                                                                                                                   verse_text
0        Genesis 34:29      טַפָּם֙                                  וְאֶת־כָּל־חֵילָ֤ם וְאֶת־כָּל־טַפָּם֙ וְאֶת־נְשֵׁיהֶ֔ם שָׁב֖וּ וַיָּבֹ֑זּוּ וְאֵ֖ת כָּל־אֲשֶׁ֥ר בַּבָּֽיִת׃
1         Genesis 43:8   טַפֵּֽנוּ׃  וַיֹּ֨אמֶר יְהוּדָ֜ה אֶל־יִשְׂרָאֵ֣ל אָבִ֗יו שִׁלְחָ֥ה הַנַּ֛עַר אִתִּ֖י וְנָק֣וּמָה וְנֵלֵ֑כָה וְנִֽחְיֶה֙ וְלֹ֣א נָמ֔וּת גַּם־אֲנַ֥חְנ...
2        Genesis 45:19    טַפְּכֶם֙  וְאַתָּ֥ה צֻוֵּ֖יתָה זֹ֣את עֲשׂ֑וּ קְחוּ־לָכֶם֩ מֵאֶ֨רֶץ מִצְרַ֜יִם עֲגָלֹ֗ות לְטַפְּכֶם֙ וְלִנְשֵׁיכֶ֔ם וּנְשָׂאתֶ֥ם אֶת־אֲבִיכֶ֖ם וּבָ...
3         Genesis 46:5      טַפָּם֙  וַיָּ֥קָם יַעֲקֹ֖ב מִבְּאֵ֣ר שָׁ֑בַע וַיִּשְׂא֨וּ בְנֵֽי־יִשְׂרָאֵ֜ל אֶת־יַעֲקֹ֣ב אֲבִיהֶ֗ם וְאֶת־טַפָּם֙ וְאֶת־נְשֵׁיהֶ֔ם בָּעֲגָלֹ֕ות ...
4        Genesis 47:12       טָּֽף׃                                            וַיְכַלְכֵּ֤ל יֹוסֵף֙ אֶת־אָבִ֣יו וְאֶת־אֶחָ֔יו וְאֵ֖ת כָּל־בֵּ֣ית אָבִ֑יו לֶ֖חֶם לְפִ֥י הַטָּֽף׃
5        Genesis 47:24   טַפְּכֶֽם׃  וְהָיָה֙ בַּתְּבוּאֹ֔ת וּנְתַתֶּ֥ם חֲמִישִׁ֖ית לְפַרְעֹ֑ה וְאַרְבַּ֣ע הַיָּדֹ֡ת יִהְיֶ֣ה לָכֶם֩ לְזֶ֨רַע הַשָּׂדֶ֧ה וּֽלְאָכְלְכֶ֛ם וְלַ...
6         Genesis 50:8      טַפָּם֙                               וְכֹל֙ בֵּ֣ית יֹוסֵ֔ף וְאֶחָ֖יו וּבֵ֣ית אָבִ֑יו רַ֗ק טַפָּם֙ וְצֹאנָ֣ם וּבְקָרָ֔ם עָזְב֖וּ בְּאֶ֥רֶץ גֹּֽשֶׁן׃
7        Genesis 50:21    טַפְּכֶ֑ם                          וְעַתָּה֙ אַל־תִּירָ֔אוּ אָנֹכִ֛י אֲכַלְכֵּ֥ל אֶתְכֶ֖ם וְאֶֽת־טַפְּכֶ֑ם וַיְנַחֵ֣ם אֹותָ֔ם וַיְדַבֵּ֖ר עַל־לִבָּֽם׃
8         Exodus 10:10    טַפְּכֶ֑ם     וַיֹּ֣אמֶר אֲלֵהֶ֗ם יְהִ֨י כֵ֤ן יְהוָה֙ עִמָּכֶ֔ם כַּאֲשֶׁ֛ר אֲשַׁלַּ֥ח אֶתְכֶ֖ם וְאֶֽת־טַפְּכֶ֑ם רְא֕וּ כִּ֥י רָעָ֖ה נֶ֥גֶד פְּנֵיכֶֽם׃
9         Exodus 10:24    טַפְּכֶ֖ם  וַיִּקְרָ֨א פַרְעֹ֜ה אֶל־מֹשֶׁ֗ה וַיֹּ֨אמֶר֙ לְכוּ֙ עִבְד֣וּ אֶת־יְהוָ֔ה רַ֛ק צֹאנְכֶ֥ם וּבְקַרְכֶ֖ם יֻצָּ֑ג גַּֽם־טַפְּכֶ֖ם יֵלֵ֥ךְ עִמ...
10        Exodus 12:37       טָּֽף׃                          וַיִּסְע֧וּ בְנֵֽי־יִשְׂרָאֵ֛ל מֵרַעְמְסֵ֖ס סֻכֹּ֑תָה כְּשֵׁשׁ־מֵאֹ֨ות אֶ֧לֶף רַגְלִ֛י הַגְּבָרִ֖ים לְבַ֥ד מִטָּֽף׃
11        Numbers 14:3    טַפֵּ֖נוּ  וְלָמָ֣ה יְ֠הוָה מֵבִ֨יא אֹתָ֜נוּ אֶל־הָאָ֤רֶץ הַזֹּאת֙ לִנְפֹּ֣ל בַּחֶ֔רֶב נָשֵׁ֥ינוּ וְטַפֵּ֖נוּ יִהְי֣וּ לָבַ֑ז הֲלֹ֧וא טֹ֦וב לָ֖נוּ ...
12       Numbers 14:31   טַ֨פְּכֶ֔ם                    וְטַ֨פְּכֶ֔ם אֲשֶׁ֥ר אֲמַרְתֶּ֖ם לָבַ֣ז יִהְיֶ֑ה וְהֵבֵיאתִ֣י אֹתָ֔ם וְיָֽדְעוּ֙ אֶת־הָאָ֔רֶץ אֲשֶׁ֥ר מְאַסְתֶּ֖ם בָּֽהּ׃
13       Numbers 16:27     טַפָּֽם׃  וַיֵּעָל֗וּ מֵעַ֧ל מִשְׁכַּן־קֹ֛רֶח דָּתָ֥ן וַאֲבִירָ֖ם מִסָּבִ֑יב וְדָתָ֨ן וַאֲבִירָ֜ם יָצְא֣וּ נִצָּבִ֗ים פֶּ֚תַח אָֽהֳלֵיהֶ֔ם וּנְשֵׁ...
14        Numbers 31:9      טַפָּ֑ם  וַיִּשְׁבּ֧וּ בְנֵי־יִשְׂרָאֵ֛ל אֶת־נְשֵׁ֥י מִדְיָ֖ן וְאֶת־טַפָּ֑ם וְאֵ֨ת כָּל־בְּהֶמְתָּ֧ם וְאֶת־כָּל־מִקְנֵהֶ֛ם וְאֶת־כָּל־חֵילָ֖ם בָּ...
15       Numbers 31:17        טָּ֑ף                                          וְעַתָּ֕ה הִרְג֥וּ כָל־זָכָ֖ר בַּטָּ֑ף וְכָל־אִשָּׁ֗ה יֹדַ֥עַת אִ֛ישׁ לְמִשְׁכַּ֥ב זָכָ֖ר הֲרֹֽגוּ׃
16       Numbers 31:18        טַּ֣ף                                                          וְכֹל֙ הַטַּ֣ף בַּנָּשִׁ֔ים אֲשֶׁ֥ר לֹא־יָדְע֖וּ מִשְׁכַּ֣ב זָכָ֑ר הַחֲי֖וּ לָכֶֽם׃
17       Numbers 32:16   טַפֵּֽנוּ׃                                       וַיִּגְּשׁ֤וּ אֵלָיו֙ וַ֣יֹּאמְר֔וּ גִּדְרֹ֥ת צֹ֛אן נִבְנֶ֥ה לְמִקְנֵ֖נוּ פֹּ֑ה וְעָרִ֖ים לְטַפֵּֽנוּ׃
18       Numbers 32:17   טַפֵּ֨נוּ֙  וַאֲנַ֜חְנוּ נֵחָלֵ֣ץ חֻשִׁ֗ים לִפְנֵי֙ בְּנֵ֣י יִשְׂרָאֵ֔ל עַ֛ד אֲשֶׁ֥ר אִם־הֲבִֽיאֹנֻ֖ם אֶל־מְקֹומָ֑ם וְיָשַׁ֤ב טַפֵּ֨נוּ֙ בְּעָרֵ֣י ה...
19       Numbers 32:24    טַפְּכֶ֔ם                                                בְּנֽוּ־לָכֶ֤ם עָרִים֙ לְטַפְּכֶ֔ם וּגְדֵרֹ֖ת לְצֹנַאֲכֶ֑ם וְהַיֹּצֵ֥א מִפִּיכֶ֖ם תַּעֲשֽׂוּ׃
20       Numbers 32:26    טַפֵּ֣נוּ                                                   טַפֵּ֣נוּ נָשֵׁ֔ינוּ מִקְנֵ֖נוּ וְכָל־בְּהֶמְתֵּ֑נוּ יִֽהְיוּ־שָׁ֖ם בְּעָרֵ֥י הַגִּלְעָֽד׃
21    Deuteronomy 1:39    טַפְּכֶם֩  וְטַפְּכֶם֩ אֲשֶׁ֨ר אֲמַרְתֶּ֜ם לָבַ֣ז יִהְיֶ֗ה וּ֠בְנֵיכֶם אֲשֶׁ֨ר לֹא־יָדְע֤וּ הַיֹּום֙ טֹ֣וב וָרָ֔ע הֵ֖מָּה יָבֹ֣אוּ שָׁ֑מָּה וְלָהֶ֣...
22    Deuteronomy 2:34        טָּ֑ף        וַנִּלְכֹּ֤ד אֶת־כָּל־עָרָיו֙ בָּעֵ֣ת הַהִ֔וא וַֽנַּחֲרֵם֙ אֶת־כָּל־עִ֣יר מְתִ֔ם וְהַנָּשִׁ֖ים וְהַטָּ֑ף לֹ֥א הִשְׁאַ֖רְנוּ שָׂרִֽיד׃
23     Deuteronomy 3:6       טָּֽף׃                    וַנַּחֲרֵ֣ם אֹותָ֔ם כַּאֲשֶׁ֣ר עָשִׂ֔ינוּ לְסִיחֹ֖ן מֶ֣לֶךְ חֶשְׁבֹּ֑ון הַחֲרֵם֙ כָּל־עִ֣יר מְתִ֔ם הַנָּשִׁ֖ים וְהַטָּֽף׃
24    Deuteronomy 3:19    טַפְּכֶם֮           רַ֠ק נְשֵׁיכֶ֣ם וְטַפְּכֶם֮ וּמִקְנֵכֶם֒ יָדַ֕עְתִּי כִּֽי־מִקְנֶ֥ה רַ֖ב לָכֶ֑ם יֵֽשְׁבוּ֙ בְּעָ֣רֵיכֶ֔ם אֲשֶׁ֥ר נָתַ֖תִּי לָכֶֽם׃
25   Deuteronomy 20:14        טַּ֨ף  רַ֣ק הַ֠נָּשִׁים וְהַטַּ֨ף וְהַבְּהֵמָ֜ה וְכֹל֩ אֲשֶׁ֨ר יִהְיֶ֥ה בָעִ֛יר כָּל־שְׁלָלָ֖הּ תָּבֹ֣ז לָ֑ךְ וְאָֽכַלְתָּ֙ אֶת־שְׁלַ֣ל אֹיְבֶ֔...
26   Deuteronomy 29:10    טַפְּכֶ֣ם                                       טַפְּכֶ֣ם נְשֵׁיכֶ֔ם וְגֵ֣רְךָ֔ אֲשֶׁ֖ר בְּקֶ֣רֶב מַחֲנֶ֑יךָ מֵחֹטֵ֣ב עֵצֶ֔יךָ עַ֖ד שֹׁאֵ֥ב מֵימֶֽיךָ׃
27   Deuteronomy 31:12        טַּ֔ף  הַקְהֵ֣ל אֶת־הָעָ֗ם הָֽאֲנָשִׁ֤ים וְהַנָּשִׁים֙ וְהַטַּ֔ף וְגֵרְךָ֖ אֲשֶׁ֣ר בִּשְׁעָרֶ֑יךָ לְמַ֨עַן יִשְׁמְע֜וּ וּלְמַ֣עַן יִלְמְד֗וּ וְ...
28         Joshua 1:14    טַפְּכֶם֮  נְשֵׁיכֶ֣ם טַפְּכֶם֮ וּמִקְנֵיכֶם֒ יֵשְׁב֕וּ בָּאָ֕רֶץ אֲשֶׁ֨ר נָתַ֥ן לָכֶ֛ם מֹשֶׁ֖ה בְּעֵ֣בֶר הַיַּרְדֵּ֑ן וְאַתֶּם֩ תַּעַבְר֨וּ חֲמֻשׁ...
29         Joshua 8:35        טַּ֔ף  לֹֽא־הָיָ֣ה דָבָ֔ר מִכֹּ֖ל אֲשֶׁר־צִוָּ֣ה מֹשֶׁ֑ה אֲשֶׁ֨ר לֹֽא־קָרָ֜א יְהֹושֻׁ֗עַ נֶ֣גֶד כָּל־קְהַ֤ל יִשְׂרָאֵל֙ וְהַנָּשִׁ֣ים וְהַטַּ֔ף...
30        Judges 18:21        טַּ֧ף                                         וַיִּפְנ֖וּ וַיֵּלֵ֑כוּ וַיָּשִׂ֨ימוּ אֶת־הַטַּ֧ף וְאֶת־הַמִּקְנֶ֛ה וְאֶת־הַכְּבוּדָּ֖ה לִפְנֵיהֶֽם׃
31        Judges 21:10       טָּֽף׃  וַיִּשְׁלְחוּ־שָׁ֣ם הָעֵדָ֗ה שְׁנֵים־עָשָׂ֥ר אֶ֛לֶף אִ֖ישׁ מִבְּנֵ֣י הֶחָ֑יִל וַיְצַוּ֨וּ אֹותָ֜ם לֵאמֹ֗ר לְ֠כוּ וְהִכִּיתֶ֞ם אֶת־יֹושְׁ...
32      2_Samuel 15:22        טַּ֖ף                וַיֹּ֧אמֶר דָּוִ֛ד אֶל־אִתַּ֖י לֵ֣ךְ וַעֲבֹ֑ר וַֽיַּעֲבֹ֞ר אִתַּ֤י הַגִּתִּי֙ וְכָל־אֲנָשָׁ֔יו וְכָל־הַטַּ֖ף אֲשֶׁ֥ר אִתֹּֽו׃
33       Jeremiah 40:7         טָ֔ף  וַיִּשְׁמְעוּ֩ כָל־שָׂרֵ֨י הַחֲיָלִ֜ים אֲשֶׁ֣ר בַּשָּׂדֶ֗ה הֵ֚מָּה וְאַנְשֵׁיהֶ֔ם כִּֽי־הִפְקִ֧יד מֶֽלֶךְ־בָּבֶ֛ל אֶת־גְּדַלְיָ֥הוּ בֶן־...
34      Jeremiah 41:16         טַף֙  וַיִּקַּח֩ יֹוחָנָ֨ן בֶּן־קָרֵ֜חַ וְכָל־שָׂרֵ֧י הַחֲיָלִ֣ים אֲשֶׁר־אִתֹּ֗ו אֵ֣ת כָּל־שְׁאֵרִ֤ית הָעָם֙ אֲשֶׁ֣ר הֵ֠שִׁיב מֵאֵ֨ת יִשְׁמָעֵ...
35       Jeremiah 43:6        טַּף֮  אֶֽת־הַ֠גְּבָרִים וְאֶת־הַנָּשִׁ֣ים וְאֶת־הַטַּף֮ וְאֶת־בְּנֹ֣ות הַמֶּלֶךְ֒ וְאֵ֣ת כָּל־הַנֶּ֗פֶשׁ אֲשֶׁ֤ר הִנִּ֨יחַ֙ נְבוּזַרְאֲדָ֣ן רַ...
36         Ezekiel 9:6         טַ֨ף  זָקֵ֡ן בָּח֣וּר וּבְתוּלָה֩ וְטַ֨ף וְנָשִׁ֜ים תַּהַרְג֣וּ לְמַשְׁחִ֗ית וְעַל־כָּל־אִ֨ישׁ אֲשֶׁר־עָלָ֤יו הַתָּו֙ אַל־תִּגַּ֔שׁוּ וּמִמִּק...
37         Esther 3:13         טַ֤ף  וְנִשְׁלֹ֨וחַ סְפָרִ֜ים בְּיַ֣ד הָרָצִים֮ אֶל־כָּל־מְדִינֹ֣ות הַמֶּלֶךְ֒ לְהַשְׁמִ֡יד לַהֲרֹ֣ג וּלְאַבֵּ֣ד אֶת־כָּל־הַ֠יְּהוּדִים מִנַּ֨...
38         Esther 8:11         טַ֣ף  אֲשֶׁר֩ נָתַ֨ן הַמֶּ֜לֶךְ לַיְּהוּדִ֣ים׀ אֲשֶׁ֣ר בְּכָל־עִיר־וָעִ֗יר לְהִקָּהֵל֮ וְלַעֲמֹ֣ד עַל־נַפְשָׁם֒ לְהַשְׁמִיד֩ וְלַהֲרֹ֨ג וּלְאַ...
39           Ezra 8:21    טַפֵּ֖נוּ  וָאֶקְרָ֨א שָׁ֥ם צֹום֙ עַל־הַנָּהָ֣ר אַהֲוָ֔א לְהִתְעַנֹּ֖ות לִפְנֵ֣י אֱלֹהֵ֑ינוּ לְבַקֵּ֤שׁ מִמֶּ֨נּוּ֙ דֶּ֣רֶךְ יְשָׁרָ֔ה לָ֥נוּ וּלְט...
40  2_Chronicles 20:13      טַפָּ֖ם                                                           וְכֹ֨ל־יְהוּדָ֔ה עֹמְדִ֖ים לִפְנֵ֣י יְהוָ֑ה גַּם־טַפָּ֖ם נְשֵׁיהֶ֥ם וּבְנֵיהֶֽם׃ פ
41  2_Chronicles 31:18      טַפָּ֧ם                 וּלְהִתְיַחֵ֗שׂ בְּכָל־טַפָּ֧ם נְשֵׁיהֶ֛ם וּבְנֵיהֶ֥ם וּבְנֹותֵיהֶ֖ם לְכָל־קָהָ֑ל כִּ֥י בֶאֱמוּנָתָ֖ם יִתְקַדְּשׁוּ־קֹֽדֶשׁ׃

# 13 - Classify the contexts<a class="anchor" id="bullet13"></a>
##### [Back to ToC](#TOC)

Context Fabric retrieves the occurrences, references, Hebrew forms, verse text, morphology, and syntax. It does **not** supply the contextual labels used below. The classification is a separate act of scholarly coding based on close reading of the 42 verses.

The assignments are stored in `context_classification_mapping.json`. They are researcher-supplied interpretations, not BHSA features or values returned by MCP. Keeping them outside the code makes changes to the scholarly coding visible in an ordinary diff.

A fresh verse-by-verse review showed that the former label *movement, settlement, or dependent care* was too broad. It combined journeys and protected residence with the materially different question of feeding a household. Every reference is now assigned to one of four broad frames:

- **conflict, captivity, or lethal judgment**;
- **household movement, displacement, or protected residence**;
- **household provision or survival**;
- **covenant, cultic, or administrative inclusion**.

The fourth frame is worth adding because Genesis 43:8; 47:12, 24; and 50:21 concern continued life, food, or provision rather than the location of the household. The distinction is small enough to remain readable and large enough to prevent four materially different verses from disappearing inside the largest group. Adding further broad frames would begin to produce one-verse categories. A narrower `context_detail` therefore records the immediate event without turning every detail into a separate count.

The mapping also gives the relevant unpointed Hebrew phrase, a contextual rendering of `טף`, a close working translation, and a brief reason for the assignment. The translations are aids to reading the Hebrew; they are not quotations from a published Bible. *Little ones* remains the normal rendering. *Household dependants* is used where `טף` functions as a wider household aggregate, while Numbers 31:17–18 and 2 Chronicles 20:13; 31:18 require still more specific wording.

The procedure is fixed when the notebook runs, but interpretive in its construction. The validation requires every retrieved reference to occur exactly once, every frame to have a definition, and every mapped Hebrew phrase to be present in its BHSA verse after pointing and cantillation are removed. An omitted, duplicated, unexpected, or textually mismatched reference stops the notebook before totals are calculated.

Two borderline decisions should remain visible. Jeremiah 41:16 belongs with conflict and captivity because the little ones are among people recovered from Ishmael, not simply a travelling group. In 2 Chronicles 31:18, `להתיחש` denotes genealogical enrollment; the verse therefore belongs to institutional inclusion, but not to public assembly in the narrower sense.

In [11]:
# Apply the explicit researcher-supplied contextual mapping
context_mapping = json.loads(CONTEXT_MAPPING_FILE.read_text(encoding="utf-8"))

assert context_mapping["mapping_type"] == "researcher-supplied interpretive classification"
assert context_mapping["input_key"] == "reference"

mapping_df = pd.DataFrame(context_mapping["occurrences"])
expected_mapping_columns = ["reference", *context_mapping["output_fields"]]
assert list(mapping_df.columns) == expected_mapping_columns

# No reference may be absent from the mapping or assigned more than once.
retrieved_references = set(taf_df["reference"])
mapped_references = set(mapping_df["reference"])
duplicate_codings = sorted(
    mapping_df.loc[mapping_df["reference"].duplicated(keep=False), "reference"].unique()
)
unclassified_references = retrieved_references - mapped_references
unexpected_references = mapped_references - retrieved_references
unexpected_frames = set(mapping_df["context_frame"]) - set(context_mapping["frame_definitions"])

assert not duplicate_codings, f"References assigned more than once: {duplicate_codings}"
assert not unclassified_references, f"Retrieved references without a frame: {sorted(unclassified_references)}"
assert not unexpected_references, f"Mapped references absent from retrieval: {sorted(unexpected_references)}"
assert not unexpected_frames, f"Frames without a definition: {sorted(unexpected_frames)}"

# Compare consonants so that the readable, unpointed phrases can be checked
# against the pointed and cantillated BHSA verse text.
def consonantal_hebrew(value: str) -> str:
    decomposed = unicodedata.normalize("NFD", value)
    return "".join(
        character
        for character in decomposed
        if unicodedata.category(character).startswith("L")
    )

phrase_check_df = taf_df[["reference", "verse_text"]].merge(
    mapping_df[["reference", "relevant_hebrew_phrase"]],
    on="reference",
    how="inner",
    validate="one_to_one",
)
phrase_mismatches = [
    row.reference
    for row in phrase_check_df.itertuples()
    if consonantal_hebrew(row.relevant_hebrew_phrase)
    not in consonantal_hebrew(row.verse_text)
]
assert not phrase_mismatches, f"Mapped Hebrew phrase not found in BHSA verse: {phrase_mismatches}"

taf_df = taf_df.merge(
    mapping_df,
    on="reference",
    how="left",
    validate="one_to_one",
)

context_counts = (
    taf_df["context_frame"]
    .value_counts()
    .rename_axis("context_frame")
    .reset_index(name="occurrences")
)
context_counts["percent"] = (
    100 * context_counts["occurrences"] / len(taf_df)
).round(1)

display(pd.Series({
    "mapping_type": context_mapping["mapping_type"],
    "mapping_file": CONTEXT_MAPPING_FILE.relative_to(REPO_ROOT).as_posix(),
    "mapping_sha256": context_mapping_sha256,
}))
display(context_counts)
classification_review_columns = [
    "reference",
    "matched_form",
    "relevant_hebrew_phrase",
    "taph_rendering",
    "working_translation",
    "context_frame",
    "context_detail",
    "classification_note",
]
classification_review_df = taf_df[classification_review_columns].copy()
display(classification_review_df)

taf_df.to_csv(
    RESULTS_DIR / "taf_occurrences_context_classified.csv",
    index=False,
    encoding="utf-8-sig",
)
classification_review_df.to_csv(
    RESULTS_DIR / "taf_context_classification_review.csv",
    index=False,
    encoding="utf-8-sig",
)

mapping_type                       researcher-supplied interpretive classification
mapping_file                    context_fabric/context_classification_mapping.json
mapping_sha256    89b8425d65c0376095a19dcc6bfcbc688ffb021177163351fbaa277e22cc66e1
dtype: str

                                              context_frame  occurrences  percent
0  household movement, displacement, or protected residence           17     40.5
1                   conflict, captivity, or lethal judgment           16     38.1
2             covenant, cultic, or administrative inclusion            5     11.9
3                           household provision or survival            4      9.5

,reference,matched_form,relevant_hebrew_phrase,taph_rendering,working_translation,context_frame,context_detail,classification_note
0,Genesis 34:29,טַפָּם֙,ואת־כל־טפם ואת־נשיהם שבו,their little ones,and they took captive all their little ones and their wives,"conflict, captivity, or lethal judgment",capture and plunder after the massacre at Shechem,"The finite verb שבו, 'they took captive', directly governs the little ones and wives."
1,Genesis 43:8,טַפֵּֽנוּ׃,ונחיה ולא נמות גם־אנחנו גם־אתה גם־טפנו,our little ones,"so that we may live and not die—we, you, and our little ones",household provision or survival,a journey undertaken so that the household may survive famine,"Travel is proposed, but the clause itself climaxes in the survival of the whole household, including the little ones."
2,Genesis 45:19,טַפְּכֶם֙,קחו־לכם מארץ מצרים עגלות לטפכם ולנשיכם,your little ones,take wagons from the land of Egypt for your little ones and your wives,"household movement, displacement, or protected residence",state-assisted household migration to Egypt,The wagons are expressly provided to transport the little ones and wives.
3,Genesis 46:5,טַפָּם֙,וישאו בני־ישראל את־יעקב אביהם ואת־טפם ואת־נשיהם בעגלות,their little ones,"the sons of Israel carried Jacob their father, their little ones, and their wives in the wagons","household movement, displacement, or protected residence",household migration from Canaan to Egypt,The little ones are named among those physically transported in the migration.
4,Genesis 47:12,טָּֽף׃,ויכלכל יוסף את־אביו ואת־אחיו ואת כל־בית אביו לחם לפי הטף,the household dependants,"Joseph provided his father, his brothers, and his father's whole household with food according to the number and needs of the dependants",household provision or survival,food allocation according to household need,לפי הטף is literally 'according to the mouth of the טף'; in context it measures household food by the number or needs of its dependants.
5,Genesis 47:24,טַפְּכֶֽם׃,ולאכלכם ולאשר בבתיכם ולאכל לטפכם,your little ones,"for your food, for those in your households, and for your little ones to eat",household provision or survival,food retained from the harvest for household consumption,The infinitive לאכל makes consumption by the little ones the immediate function.
6,Genesis 50:8,טַפָּם֙,רק טפם וצאנם ובקרם עזבו בארץ גשן,their little ones,"they left only their little ones, flocks, and herds in the land of Goshen","household movement, displacement, or protected residence",dependants left in Goshen during the funeral journey,The little ones remain in the settled place while the adults travel to Canaan.
7,Genesis 50:21,טַפְּכֶ֑ם,אנכי אכלכל אתכם ואת־טפכם,your little ones,I myself will provide for you and your little ones,household provision or survival,Joseph's promise of continuing material support,"The verb אכלכל, 'I will provide', directly governs the brothers and their little ones."
8,Exodus 10:10,טַפְּכֶ֑ם,יהי כן יהוה עמכם כאשר אשלח אתכם ואת־טפכם,your household dependants,May YHWH indeed be with you if I ever let you and your household dependants go,"household movement, displacement, or protected residence",Pharaoh's sarcastic rejection of a departure with dependants,The issue is who may leave Egypt; טף summarizes the dependent household members included in the proposed departure.
9,Exodus 10:24,טַפְּכֶ֖ם,רק צאנכם ובקרכם יצג גם־טפכם ילך עמכם,your household dependants,only your flocks and herds must remain; your household dependants may also go with you,"household movement, displacement, or protected residence",permission for dependants to depart while livestock is retained,The verb ילך and prepositional phrase עמכם make accompanied movement explicit.
10,Exodus 12:37,טָּֽף׃,כשש־מאות אלף רגלי הגברים לבד מטף,household dependants,"about six hundred thousand adult men on foot, apart from the household dependants","household movement, displacement, or protected residence",the exodus population counted apart from adult men,"Because הגברים counts the adult men, מטף most naturally covers the accompanying dependent population rather than one precise age band."
11,Numbers 14:3,טַפֵּ֖נוּ,נשינו וטפנו יהיו לבז,our little ones,our wives and our little ones will become plunder,"conflict, captivity, or lethal judgment",feared capture during attempted conquest,"The feared predicate יהיו לבז, 'will become plunder', determines the primary frame."
12,Numbers 14:31,טַ֨פְּכֶ֔ם,וטפכם אשר אמרתם לבז יהיה והביאתי אתם,your little ones,"your little ones, whom you said would become plunder—I will bring them in","conflict, captivity, or lethal judgment",divine reversal of the feared capture,"The verse reverses the threat of capture, but לבז still supplies the local contrast and therefore the primary frame."
13,Numbers 16:27,טַפָּֽם׃,ודתן ואבירם יצאו נצבים פתח אהליהם ונשיהם ובניהם וטפם,their little ones,"Dathan and Abiram came out and stood at the entrances of their tents, with their wives, their sons, and their little ones","conflict, captivity, or lethal judgment",households exposed to the judgment of Korah's company,The list locates the little ones within households about to be overtaken by divine judgment; it is not a neutral assembly.
14,Numbers 31:9,טַפָּ֑ם,וישבו בני־ישראל את־נשי מדין ואת־טפם,their little ones,the Israelites took captive the women of Midian and their little ones,"conflict, captivity, or lethal judgment",capture of Midian's civilian population,"The verb וישבו, 'they took captive', directly governs both groups."
15,Numbers 31:17,טָּ֑ף,הרגו כל־זכר בטף,the male children among the little ones,kill every male among the little ones,"conflict, captivity, or lethal judgment",order to kill male children among the captives,The phrase זכר בטף explicitly selects the male subset within the collective טף.
16,Numbers 31:18,טַּ֣ף,וכל הטף בנשים אשר לא־ידעו משכב זכר החיו לכם,the female children among the little ones,but all the female children among the little ones who have not known sexual relations with a male—keep alive for yourselves,"conflict, captivity, or lethal judgment",order to spare female children among the captives,The phrase הטף בנשים selects the female subset of טף and contrasts their survival with the killing ordered in the preceding verse.
17,Numbers 32:16,טַפֵּֽנוּ׃,גדרת צאן נבנה למקננו פה וערים לטפנו,our household dependants,we will build sheepfolds here for our livestock and towns for our household dependants,"household movement, displacement, or protected residence",settlements prepared for dependants east of the Jordan,The towns provide settled protection while the fighting men cross the Jordan.
18,Numbers 32:17,טַפֵּ֨נוּ֙,וישב טפנו בערי המבצר מפני ישבי הארץ,our household dependants,our household dependants will remain in the fortified towns because of the inhabitants of the land,"household movement, displacement, or protected residence",protected residence during the Transjordanian military campaign,The verbs and location describe noncombatants remaining under protection while the armed men depart.
19,Numbers 32:24,טַפְּכֶ֔ם,בנו־לכם ערים לטפכם וגדרת לצנאכם,your household dependants,build towns for your household dependants and enclosures for your flocks,"household movement, displacement, or protected residence",towns built for dependants before military departure,This instruction repeats the settlement arrangement of Numbers 32:16–17.
20,Numbers 32:26,טַפֵּ֣נוּ,טפנו נשינו מקננו וכל־בהמתנו יהיו־שם בערי הגלעד,our little ones,"our little ones, our wives, our livestock, and all our animals will remain there in the towns of Gilead","household movement, displacement, or protected residence",little ones and wives left in the Gileadite towns,"Here wives are listed separately, so 'little ones' is more precise than the broader 'dependants'."
21,Deuteronomy 1:39,טַפְּכֶם֩,וטפכם אשר אמרתם לבז יהיה ובניכם אשר לא־ידעו היום טוב ורע המה יבאו שמה,your little ones,"your little ones, whom you said would become plunder, and your sons who today do not know good from evil—they will enter there","conflict, captivity, or lethal judgment",reversal of the wilderness generation's fear of capture,The verse recalls the threatened-plunder formula while promising the younger generation entry into the land.
22,Deuteronomy 2:34,טָּ֑ף,ונחרם את־כל־עיר מתם והנשים והטף לא השארנו שריד,the little ones,"we put every town under the ban—men, women, and little ones; we left no survivor","conflict, captivity, or lethal judgment",the population of Sihon's towns placed under the ban,"The verb ונחרם and the statement that no survivor remained make this a case of lethal conquest, not merely population movement."
23,Deuteronomy 3:6,טָּֽף׃,החרם כל־עיר מתם הנשים והטף,the little ones,"putting every town under the ban—men, women, and little ones","conflict, captivity, or lethal judgment",the population of Og's towns placed under the ban,"As in Deuteronomy 2:34, טף occurs inside the population formula governed by החרם."
24,Deuteronomy 3:19,טַפְּכֶם֮,רק נשיכם וטפכם ומקנכם ידעתי כי־מקנה רב לכם ישבו בעריכם אשר נתתי לכם,your little ones,"only your wives, your little ones, and your livestock—I know that you have much livestock—shall remain in the towns that I have given you","household movement, displacement, or protected residence",families remaining in Transjordan while the fighting men cross,The little ones are part of the noncombatant household population that remains settled.
25,Deuteronomy 20:14,טַּ֨ף,רק הנשים והטף והבהמה וכל אשר יהיה בעיר כל־שללה תבז לך,the little ones,"but the women, the little ones, the livestock, and everything in the city—all its spoil—you may take as plunder","conflict, captivity, or lethal judgment",women and little ones treated as spoil after a city's defeat,The rule expressly places the little ones within the captured population and spoil of war.
26,Deuteronomy 29:10,טַפְּכֶ֣ם,טפכם נשיכם וגרך אשר בקרב מחניך,your little ones,"your little ones, your wives, and your resident alien who is within your camp","covenant, cultic, or administrative inclusion",the covenant community standing before YHWH,The verse continues the list of those standing before YHWH to enter the covenant; טף is part of the covenant public.
27,Deuteronomy 31:12,טַּ֔ף,הקהל את־העם האנשים והנשים והטף וגרך אשר בשעריך למען ישמעו ולמען ילמדו,the little ones,"assemble the people—the men, the women, the little ones, and your resident alien within your gates—so that they may hear and so that the...","covenant, cultic, or administrative inclusion",the septennial public reading of Torah,The little ones are grammatically part of the object of הקהל and of the plural audience for the purpose clauses.
28,Joshua 1:14,טַפְּכֶם֮,נשיכם טפכם ומקניכם ישבו בארץ אשר נתן לכם משה בעבר הירדן,your little ones,"your wives, your little ones, and your livestock shall remain in the land Moses gave you beyond the Jordan","household movement, displacement, or protected residence",families remaining in Transjordan while warriors cross,The verse restates the Transjordanian division between settled households and crossing warriors.
29,Joshua 8:35,טַּ֔ף,נגד כל־קהל ישראל והנשים והטף והגר ההלך בקרבם,the little ones,"before the whole assembly of Israel, including the women, the little ones, and the resident alien who lived among them","covenant, cultic, or administrative inclusion",public Torah reading before the entire assembly,The phrase identifies the little ones as present within the audience before whom Joshua reads Moses' command.
30,Judges 18:21,טַּ֧ף,וישימו את־הטף ואת־המקנה ואת־הכבודה לפניהם,the little ones,"they placed the little ones, the livestock, and the goods ahead of them","household movement, displacement, or protected residence",dependants positioned at the front of a migrating convoy,The little ones' position within the moving convoy is the immediate narrative concern.
31,Judges 21:10,טָּֽף׃,לכו והכיתם את־יושבי יבש גלעד לפי־חרב והנשים והטף,the little ones,"go and strike the inhabitants of Jabesh-gilead with the edge of the sword, including the women and the little ones","conflict, captivity, or lethal judgment",an ordered punitive massacre at Jabesh-gilead,Women and little ones fall within the stated scope of the lethal command.
32,2_Samuel 15:22,טַּ֖ף,ויעבר אתי הגתי וכל־אנשיו וכל־הטף אשר אתו,all the little ones,Ittai the Gittite crossed over with all his men and all the little ones who were with him,"household movement, displacement, or protected residence",Ittai's household retinue crossing during David's flight,The little ones accompany a displaced military retinue rather than participate as combatants.
33,Jeremiah 40:7,טָ֔ף,הפקיד אתו אנשים ונשים וטף ומדלת הארץ מאשר לא־הגלו בבלה,little ones,"[the king of Babylon] placed under him men, women, little ones, and some of the poorest of the land who had not been exiled to Babylon","household movement, displacement, or protected residence",a post-conquest civilian remnant placed under Gedaliah,The little ones belong to the non-exiled civilian remnant; displacement and remaining in the land dominate the setting.
34,Jeremiah 41:16,טַף֙,ונשים וטף וסרסים אשר השיב מגבעון,little ones,"and women, little ones, and court officials whom he brought back from Gibeon","conflict, captivity, or lethal judgment",civilians recovered from a political captor,"The repeated השיב describes recovery from Ishmael's captivity, so the earlier movement classification understated the conflict setting."
35,Jeremiah 43:6,טַּף֮,את־הגברים ואת־הנשים ואת־הטף ואת־בנות המלך ואת כל־הנפש אשר הניח נבוזראדן,the little ones,"the men, the women, the little ones, the king's daughters, and every person whom Nebuzaradan had left behind","household movement, displacement, or protected residence",the surviving population taken in the flight to Egypt,"Within Jeremiah 43:5–7 this enumerated remnant is taken to Egypt, making forced displacement the controlling episode."
36,Ezekiel 9:6,טַ֨ף,זקן בחור ובתולה וטף ונשים תהרגו למשחית,little ones,"old man, young man, young woman, little ones, and women—you shall kill them to destruction","conflict, captivity, or lethal judgment",visionary judgment against Jerusalem's population,The imperative תהרגו includes טף in the population exposed to visionary judgment.
37,Esther 3:13,טַ֤ף,להשמיד להרג ולאבד את־כל־היהודים מנער ועד־זקן טף ונשים ביום אחד,little ones,"to destroy, kill, and annihilate all the Jews, from youth to old man, little ones and women, in a single day","conflict, captivity, or lethal judgment",the royal decree to annihilate the Jews,The little ones are explicitly included in the target population of the annihilation decree.
38,Esther 8:11,טַ֣ף,להקהל ולעמד על־נפשם להשמיד ולהרג ולאבד את־כל־חיל עם ומדינה הצרים אתם טף ונשים,little ones,"to assemble and stand for their lives, and to destroy, kill, and annihilate every armed force of people or province attacking them, incl...","conflict, captivity, or lethal judgment",the counter-decree authorizing lethal defense and plunder,"Although להקהל occurs, this is armed mobilization. The syntax of הצרים אתם טף ונשים is disputed: the working translation includes little..."
39,Ezra 8:21,טַפֵּ֖נוּ,לבקש ממנו דרך ישרה לנו ולטפנו ולכל־רכושנו,our little ones,"to seek from him a safe road for us, our little ones, and all our possessions","household movement, displacement, or protected residence",a fast seeking divine protection for a journey,"The requested דרך ישרה concerns safe travel for the full caravan, including the little ones."
40,2_Chronicles 20:13,טַפָּ֖ם,וכל־יהודה עמדים לפני יהוה גם־טפם נשיהם ובניהם,their small children,"all Judah was standing before YHWH, including their small children, their wives, and their sons","covenant, cultic, or administrative inclusion",the whole community standing before YHWH in crisis,The little ones are present in a communal act of standing before YHWH; their distinction from בנים supports the narrower rendering 'smal...
41,2_Chronicles 31:18,טַפָּ֧ם,ולהתיחש בכל־טפם נשיהם ובניהם ובנותיהם לכל־קהל,their small children,"and [the genealogical enrollment included] all their small children, their wives, their sons, and their daughters—the whole assembly","covenant, cultic, or administrative inclusion",genealogical registration for cultic distributions,"The governing infinitive להתיחש denotes genealogical enrollment, not attendance at an assembly; the frame records institutional inclusio..."

## 13.1 - What the distribution does—and does not—show<a class="anchor" id="bullet13x1"></a>
##### [Back to ToC](#TOC)

The reviewed coding makes a broad pattern visible:

- 17 occurrences concern household movement, displacement, or protected residence;
- 16 concern conflict, captivity, or lethal judgment;
- five concern covenantal, cultic, or administrative inclusion;
- four concern household provision or survival.

For counting purposes each verse receives one primary frame. That does not mean that the frames are semantically airtight. Numbers 14:31, for example, combines threatened capture with anticipated movement into the land. Its place in the conflict/captivity set records the dominant feature selected for this comparison; it does not erase the movement motif. The `context_detail` and `classification_note` columns preserve that local complexity.

Within this coding, Deuteronomy 31:12 stands in a relatively small group. It places a category often associated with dependent household members and vulnerable noncombatants inside an auditory covenant-renewal institution.

The totals summarize the stated assignments; they do not independently prove a lexical definition. The scheme has also not been tested by a second coder. Its value lies instead in the complete, inspectable mapping: another researcher can move a disputed reference, rerun the cell, and see precisely how the distribution changes.

# 14 - Test the association with women and resident aliens<a class="anchor" id="bullet14"></a>
##### [Back to ToC](#TOC)

The audience formula can be measured:

- How often does a `טף` verse also contain the lexeme “woman”?
- How often does it also contain `גר`?
- Which passages contain all three?

This is especially useful because `נשים + טף` is common in household and war lists, whereas `טף + גר` is rare.

In [12]:
# Test the association with women and resident aliens
taf_and_woman = await mcp_call(
    "search",
    {
        "template": f'''verse
  word lex_utf8={H['woman']}
  word lex_utf8={H['taf']}''',
        "return_type": "passages",
        "limit": 100,
        "max_override": True,
        "corpus": "bhsa",
    },
)
taf_and_ger = await mcp_call(
    "search",
    {
        "template": f'''verse
  word lex_utf8={H['taf']}
  word lex_utf8={H['ger']}''',
        "return_type": "passages",
        "limit": 100,
        "max_override": True,
        "corpus": "bhsa",
    },
)
taf_woman_ger = await mcp_call(
    "search",
    {
        "template": f'''verse
  word lex_utf8={H['woman']}
  word lex_utf8={H['taf']}
  word lex_utf8={H['ger']}''',
        "return_type": "passages",
        "limit": 100,
        "max_override": True,
        "corpus": "bhsa",
    },
)

cooccurrence_summary = pd.DataFrame(
    [
        {"pattern": "all טף verses", "count": len(taf_df), "share_of_taf": 1.0},
        {
            "pattern": "טף + אשׁה in one verse",
            "count": taf_and_woman["total_count"],
            "share_of_taf": taf_and_woman["total_count"] / len(taf_df),
        },
        {
            "pattern": "טף + גר in one verse",
            "count": taf_and_ger["total_count"],
            "share_of_taf": taf_and_ger["total_count"] / len(taf_df),
        },
        {
            "pattern": "אשׁה + טף + גר in one verse",
            "count": taf_woman_ger["total_count"],
            "share_of_taf": taf_woman_ger["total_count"] / len(taf_df),
        },
    ]
)
cooccurrence_summary["share_of_taf"] = (100 * cooccurrence_summary["share_of_taf"]).round(1)
display(cooccurrence_summary)
display(pd.DataFrame(taf_and_ger["passages"])[["reference", "text"]])

                       pattern  count  share_of_taf
0                all טף verses     42         100.0
1       טף + אשׁה in one verse     26          61.9
2         טף + גר in one verse      3           7.1
3  אשׁה + טף + גר in one verse      3           7.1

           reference                                                                                                                                         text
0  Deuteronomy 29:10                                      טַפְּכֶ֣ם נְשֵׁיכֶ֔ם וְגֵ֣רְךָ֔ אֲשֶׁ֖ר בְּקֶ֣רֶב מַחֲנֶ֑יךָ מֵחֹטֵ֣ב עֵצֶ֔יךָ עַ֖ד שֹׁאֵ֥ב מֵימֶֽיךָ׃
1  Deuteronomy 31:12  הַקְהֵ֣ל אֶת־הָעָ֗ם הָֽאֲנָשִׁ֤ים וְהַנָּשִׁים֙ וְהַטַּ֔ף וְגֵרְךָ֖ אֲשֶׁ֣ר בִּשְׁעָרֶ֑יךָ לְמַ֨עַן יִשְׁמְע֜וּ וּלְמַ֣עַן יִלְמְד֗וּ וְ...
2        Joshua 8:35  לֹֽא־הָיָ֣ה דָבָ֔ר מִכֹּ֖ל אֲשֶׁר־צִוָּ֣ה מֹשֶׁ֑ה אֲשֶׁ֨ר לֹֽא־קָרָ֜א יְהֹושֻׁ֗עַ נֶ֣גֶד כָּל־קְהַ֤ל יִשְׂרָאֵל֙ וְהַנָּשִׁ֣ים וְהַטַּ֔ף...

## 14.1 - The distinctive covenant triad<a class="anchor" id="bullet14x1"></a>
##### [Back to ToC](#TOC)

The local BHSA search returns exactly three verses where `טף` and `גר` occur together:

1. **Deuteronomy 29:10** — the covenant community standing before YHWH;
2. **Deuteronomy 31:12** — the septennial Torah assembly;
3. **Joshua 8:35** — narrated public reading before the entire assembly.

All three also mention women. This is more historically suggestive than the common `women + טף` pairing by itself.

**Literary inference:** the Deuteronomic/Deuteronomistic corpus uses the combination of women, dependents, and resident alien to represent a maximally inclusive covenant public. The resident alien extends the assembly beyond genealogical Israel; `טף` extends it beyond autonomous adult participants; women prevent “all Israel” from collapsing into the male military or landholding body.

**Caution:** “inclusive” here describes ritual and rhetorical incorporation. It does not by itself establish equal legal power, literacy, office, or social status.

# 15 - Quantify syntactic roles across all occurrences<a class="anchor" id="bullet15"></a>
##### [Back to ToC](#TOC)

We ask Context Fabric for distributions of the phrase containing `טף` and the clause containing that phrase.

The result helps characterize the term's discourse behavior:

- it is often an object—people captured, moved, fed, threatened, or assembled;
- it can be a subject when dependents remain, stand, or are enumerated;
- its clauses are split between quotation and narrative domains.

The term is thus not confined to legal lists. It moves between narration and reported command, which weakens any attempt to define it from one genre alone.

In [13]:
# Quantify syntactic roles across all occurrences
taf_phrase_stats = await mcp_call(
    "search",
    {
        "template": f'''p:phrase
  w:word lex_utf8={H['taf']}''',
        "return_type": "statistics",
        "aggregate_features": ["function", "typ", "lex_utf8", "gloss"],
        "group_by_section": True,
        "top_n": 100,
        "corpus": "bhsa",
    },
)
taf_clause_stats = await mcp_call(
    "search",
    {
        "template": f'''c:clause
  w:word lex_utf8={H['taf']}''',
        "return_type": "statistics",
        "aggregate_features": ["typ", "domain", "lex_utf8", "gloss"],
        "group_by_section": True,
        "top_n": 100,
        "corpus": "bhsa",
    },
)

phrase_distributions = taf_phrase_stats["nodes"]["0_phrase"]["distributions"]
clause_distributions = taf_clause_stats["nodes"]["0_clause"]["distributions"]

display(Markdown("### Phrase function"))
display(pd.DataFrame(phrase_distributions["function"]))
display(Markdown("### Phrase type"))
display(pd.DataFrame(phrase_distributions["typ"]))
display(Markdown("### Clause discourse domain"))
display(pd.DataFrame(clause_distributions["domain"]))
display(Markdown("### Distribution by biblical book"))
display(pd.DataFrame(taf_phrase_stats["section_distribution"]["book"]))

### Phrase function

  value  count
0  Objc     21
1  Subj     11
2  Cmpl      4
3  Adju      4
4  Frnt      2

### Phrase type

  value  count
0    NP     21
1    PP     19
2  PPrP      1
3  PrNP      1

### Clause discourse domain

  value  count
0     Q     22
1     N     20

### Distribution by biblical book

           value  count
0        Numbers     10
1        Genesis      8
2    Deuteronomy      7
3         Exodus      3
4       Jeremiah      3
5         Joshua      2
6         Judges      2
7         Esther      2
8   2_Chronicles      2
9       2_Samuel      1
10       Ezekiel      1
11          Ezra      1

# 16 - Historical-critical synthesis<a class="anchor" id="bullet16"></a>
##### [Back to ToC](#TOC)

## 16.1 - Lexical result: dependent collective, not an exact age bracket<a class="anchor" id="bullet16x1"></a>
##### [Back to ToC](#TOC)

BHSA finds 42 instances of `טף`. It analyzes every occurrence as masculine singular, even when English idiom requires a plural. The forms may carry pronominal suffixes—“their `טף`,” “your `טף`,” “our `טף`”—which reinforces the household/dependency relation.

The contexts repeatedly oppose or coordinate `טף` with adults able to fight, travel independently, negotiate, or hold responsibility. “Little ones” is defensible, but “dependents” or “young dependents” often better preserves the social function. The corpus does **not** give an age threshold. Numbers 31:17–18 can subdivide the category by sex, and other passages coordinate `טף` with `בנים`, showing that the semantic boundaries are contextual rather than a modern census category.

This contextual flexibility is not a new meaning inferred from the four frames. Brown–Driver–Briggs describes `טף` as a masculine collective for children and notes several household passages in which women are included or implied. Athalya Brenner likewise calls it a non-gendered collective noun. These lexical observations justify varying the English gloss, but they do not assign the contextual frames; those assignments still depend on the syntax and episode of each verse.

## 16.2 - Rhetorical result: `כל־העם` is unpacked<a class="anchor" id="bullet16x2"></a>
##### [Back to ToC](#TOC)

Deuteronomy 31:12 first says “assemble the people” and then appositionally specifies men, women, `טף`, and resident alien. The list prevents an elite or military reading of “the people.” It makes the covenant public include:

- adult Israelite men;
- adult Israelite women;
- dependent/non-autonomous household members;
- resident outsiders incorporated into local Israelite life.

The `טף` are not merely present because parents need childcare. At the level of the sentence, they belong to the object of the assembly command, and the plural purpose chain is predicated of the assembled public.

## 16.3 - Pedagogical result: hearing precedes durable obedience<a class="anchor" id="bullet16x3"></a>
##### [Back to ToC](#TOC)

Verse 12 moves from hearing and learning to fearing YHWH, keeping, and doing the Torah. Verse 13 repeats hearing/learning/fearing for “their children who have not known.” The ceremony therefore imagines covenant knowledge as periodically renewed, orally transmitted, embodied in attendance, and extended across generations.

This does not require every infant to comprehend a legal recitation proposition by proposition. The text works at a collective level. Different hearers may participate with different cognitive capacities while belonging to the same covenant event.

## 16.4 - Literary result: Deuteronomy 29 → Deuteronomy 31 → Joshua 8<a class="anchor" id="bullet16x4"></a>
##### [Back to ToC](#TOC)

The rare `טף + גר` co-occurrence links three scenes:

- covenant standing (Deut 29);
- commanded periodic reading (Deut 31);
- narrated reading and covenant ceremony (Josh 8).

This sequence fits a Deuteronomic/Deuteronomistic program in which written Torah becomes publicly authoritative through recitation before a totalized community. Joshua 8:35 functions literarily as a realization of Mosaic Torah ideology, whether or not it preserves an independent archival report of an early ceremony.

## 16.5 - Social-historical result: a counterfactual public<a class="anchor" id="bullet16x5"></a>
##### [Back to ToC](#TOC)

In ordinary `טף` contexts, dependents are carried, left in protected settlements, fed, captured, threatened, or killed. Deuteronomy 31 converts that social dependence into ritual membership. Those least likely to be counted as autonomous political actors are nonetheless required for the covenant public to be complete.

“Counterfactual” is useful here: the assembly imagines Israel not as the subset able to march, own, fight, or read, but as everyone who must live under and transmit the Torah.

## 16.6 - Compositional and institutional questions<a class="anchor" id="bullet16x6"></a>
##### [Back to ToC](#TOC)

Historical-critical scholarship commonly relates Deuteronomy's written-Torah ideology, central sanctuary, covenant rhetoric, and public instruction to late-monarchic and exilic scribal formation, often in conversation with the Josianic reform narrative and later Deuteronomistic editing. Deuteronomy 31 itself is compositionally layered, and assignments of verses 1–13 to particular editions vary.

The corpus results cannot choose among detailed redaction models. They do support a more limited claim: Deuteronomy 31:10–13 is thoroughly integrated into the book's program of centralized covenant instruction and intergenerational Torah transmission.

The command also does not prove that a septennial national ceremony was regularly performed in the form described. Prescriptive texts may project ideals, authorize innovations by Mosaic attribution, reshape remembered practice, or formalize an institution. Joshua's narrative fulfillment is internal literary evidence, not external corroboration.

## 16.7 - Why Sukkot after the sabbatical year?<a class="anchor" id="bullet16x7"></a>
##### [Back to ToC](#TOC)

The chosen moment joins several symbolic and practical horizons:

- pilgrimage to the chosen place already gathers a wide population;
- the agricultural year has turned;
- the sabbatical cycle foregrounds land, release, dependence, and YHWH's ownership;
- public reading renews the normative order for the next seven-year cycle.

The `טף` embody the future across that cycle. Many will mature before the next assembly. Verse 13 makes precisely this temporal bridge explicit.

# 17 - Conclusions<a class="anchor" id="bullet17"></a>
##### [Back to ToC](#TOC)

1. `טף` is collective and socially functional. The 42 BHSA occurrences favor “dependents / young dependents / those unable to march” over a narrowly defined age class.
2. Deuteronomy 31:12 is a marked reuse of the term. A category usually exposed in movement, war, capture, and care is incorporated into a covenant-learning assembly.
3. The syntax gives `טף` full audience membership. Men, women, `טף`, and resident alien form the object of “assemble”; the purpose chain addresses the plural collective.
4. Verse 13 supplies the intergenerational logic. Children who “have not known” hear, learn, and acquire covenant fear for life in the land.
5. The rare `טף + גר` triad is literarily significant. It occurs only in Deuteronomy 29:10, Deuteronomy 31:12, and Joshua 8:35, joining covenant constitution, periodic Torah reading, and narrated fulfillment.
6. The passage constructs an unusually broad covenant public. Inclusion in ritual hearing does not erase social hierarchy, but it refuses to identify covenant Israel only with autonomous adult males.
7. Historical performance remains unproven. The text is strong evidence for a scribal-theological program of public Torah and collective identity; it is not by itself proof of a continuously observed early institution.

## 17.1 - Compact answer to the research question<a class="anchor" id="bullet17x1"></a>
##### [Back to ToC](#TOC)

The explicit `טף` in Deuteronomy 31:12 makes the covenant assembly coextensive with the whole lived community, including those who cannot yet function as independent, military, literate, or juridical actors. Historically and literarily, their presence turns public Torah reading into a mechanism of intergenerational identity formation. The term's wider distribution adds force to the command: the dependents whom narratives normally carry, protect, capture, feed, or endanger are here made indispensable hearers within the imagined covenant public.

# 18 - Limitations and next investigations<a class="anchor" id="bullet18"></a>
##### [Back to ToC](#TOC)

## 18.1 - Limitations<a class="anchor" id="bullet18x1"></a>
##### [Back to ToC](#TOC)

- BHSA represents the medieval Masoretic textual tradition and ETCBC linguistic analysis.
- This notebook does not collate the Septuagint, Samaritan Pentateuch, Dead Sea Scrolls, or medieval manuscripts.
- Lexical distribution cannot independently date Deuteronomy 31:10–13.
- The four contextual frames and their narrower details remain interpretive and have not been tested by a second coder.
- “Inclusive” describes the composition of the ritual audience, not modern egalitarian citizenship.
- The notebook does not infer literacy rates from a command to hear a written Torah read aloud.

## 18.2 - Strong next steps<a class="anchor" id="bullet18x2"></a>
##### [Back to ToC](#TOC)

1. Compare Greek renderings of `טף` in all 42 passages, especially Deuteronomy 31:12 and Joshua 8:35.
2. Examine textual variants for Deuteronomy 31:10–13 and Joshua 8:34–35.
3. Compare ancient Near Eastern treaty-deposition and periodic-public-reading practices.
4. Test the broader Deuteronomic audience vocabulary: `קהל`, `עם`, `גר`, women, sons, and “all Israel.”
5. Separate compositional layers in Deuteronomy 31 and ask whether verses 10–13 presuppose Deuteronomy alone or a broader Torah.
6. Study later reception—Mishnah Sotah 7:8 and Babylonian Talmud Hagigah 3a—after, not instead of, the historical-critical corpus analysis.

# 19 - Data used<a class="anchor" id="bullet19"></a>
##### [Back to ToC](#TOC)


- Context Fabric, [GitHub repository](https://github.com/Context-Fabric/context-fabric).
- ETCBC, *Biblia Hebraica Stuttgartensia (Amstelodamensis)*, [BHSA GitHub repository](https://github.com/ETCBC/bhsa), version directory `tf/2021`; dataset DOI [10.17026/dans-z6y-skyh](https://doi.org/10.17026/dans-z6y-skyh).
- ETCBC project documentation, “Coding the Hebrew Bible,” DOI [10.1163/24523666-01000011](https://doi.org/10.1163/24523666-01000011).
- Brown–Driver–Briggs, entry [`טף`](https://biblehub.com/strongs/hebrew/2945.htm), consulted for the collective noun and its context-sensitive range.
- Athalya Brenner, [“Regulating ‘sons’ and ‘daughters’ in the Torah and in Proverbs: Some Preliminary Insights”](https://jhsonline.org/index.php/jhs/article/download/5753/4806/12785), especially the description of `טף` as a non-gendered collective noun.

# 20 - Final check<a class="anchor" id="bullet20"></a>
##### [Back to ToC](#TOC)

Finally, let us check the points that should remain true when the notebook is rerun against the same BHSA version. If the corpus or query behaviour changes, the assertions below will stop the notebook rather than leave us with a misleading result.

In [14]:
# Final check
audit = {
    "local_endpoint": MCP_SSE_URL,
    "bhsa_commit": bhsa_commit,
    "context_mapping_file": CONTEXT_MAPPING_FILE.relative_to(REPO_ROOT).as_posix(),
    "context_mapping_sha256": context_mapping_sha256,
    "context_mapping_type": context_mapping["mapping_type"],
    "classification_review_file": (RESULTS_DIR / "taf_context_classification_review.csv").relative_to(REPO_ROOT).as_posix(),
    "context_frame_counts": {
        row.context_frame: int(row.occurrences)
        for row in context_counts.itertuples()
    },
    "classified_context_detail_rows": int(taf_df["context_detail"].notna().sum()),
    "validated_hebrew_phrase_rows": len(phrase_check_df) - len(phrase_mismatches),
    "working_translation_rows": int(taf_df["working_translation"].notna().sum()),
    "taf_total": len(taf_df),
    "taf_with_woman": taf_and_woman["total_count"],
    "taf_with_ger": taf_and_ger["total_count"],
    "taf_with_woman_and_ger": taf_woman_ger["total_count"],
    "taf_ger_references": [item["reference"] for item in taf_and_ger["passages"]],
    "deut_31_12_audience_matches": audience_result["total_count"],
    "deut_31_12_purpose_matches": purpose_result["total_count"],
    "deut_31_13_chain_matches": verse13_result["total_count"],
}

assert audit["taf_total"] == 42
assert sum(audit["context_frame_counts"].values()) == 42
assert audit["classified_context_detail_rows"] == 42
assert audit["validated_hebrew_phrase_rows"] == 42
assert audit["working_translation_rows"] == 42
assert audit["taf_with_woman"] == 26
assert audit["taf_with_ger"] == 3
assert audit["taf_with_woman_and_ger"] == 3
assert audit["taf_ger_references"] == [
    "Deuteronomy 29:10",
    "Deuteronomy 31:12",
    "Joshua 8:35",
]
assert audit["deut_31_12_audience_matches"] == 1
assert audit["deut_31_12_purpose_matches"] == 1
assert audit["deut_31_13_chain_matches"] == 1

(RESULTS_DIR / "audit.json").write_text(
    json.dumps(audit, ensure_ascii=False, indent=2) + "\n",
    encoding="utf-8",
)
display(pd.Series(audit, name="value").to_frame())
print("Audit passed.")

                                                                                                                                                                      value
local_endpoint                                                                                                                                    http://127.0.0.1:8765/sse
bhsa_commit                                                                                                                        4db00e2157915495e1a4d3d57e41223df24775da
context_mapping_file                                                                                                     context_fabric/context_classification_mapping.json
context_mapping_sha256                                                                                     89b8425d65c0376095a19dcc6bfcbc688ffb021177163351fbaa277e22cc66e1
context_mapping_type                                                                                                        researcher-supplied interpretive classification
classification_review_file                                                                                     context_fabric/results/taf_context_classification_review.csv
context_frame_counts            {'household movement, displacement, or protected residence': 17, 'conflict, captivity, or lethal judgment': 16, 'covenant, cultic, or ad...
classified_context_detail_rows                                                                                                                                           42
validated_hebrew_phrase_rows                                                                                                                                             42
working_translation_rows                                                                                                                                                 42
taf_total                                                                                                                                                                42
taf_with_woman                                                                                                                                                           26
taf_with_ger                                                                                                                                                              3
taf_with_woman_and_ger                                                                                                                                                    3
taf_ger_references                                                                                                      [Deuteronomy 29:10, Deuteronomy 31:12, Joshua 8:35]
deut_31_12_audience_matches                                                                                                                                               1
deut_31_12_purpose_matches                                                                                                                                                1
deut_31_13_chain_matches                                                                                                                                                  1

Audit passed.

# 21 - Required libraries<a class="anchor" id="bullet21"></a>
##### [Back to ToC](#TOC)

The tested package versions are recorded in `requirements.txt`. Install them
in the repository-local environment before running the notebook:

```powershell
& ".\.context-fabric-venv\Scripts\python.exe" -m pip install -r ".\context_fabric\requirements.txt"
```

# 22 - Notebook details<a class="anchor" id="bullet22"></a>
##### [Back to ToC](#TOC)

<div style="float: left;">
  <table>
    <tr><td><strong>Author</strong></td><td>Tony Jurg</td></tr>
    <tr><td><strong>Version</strong></td><td>1.3</td></tr>
    <tr><td><strong>Date</strong></td><td>7 August 2026</td></tr>
  </table>
</div>