# Hakhel reception history

## Table of contents (ToC)<a class="anchor" id="TOC"></a>

* <a href="#bullet1">1 - Purpose, method and limits</a>
* <a href="#bullet2">2 - Set up dependencies</a>
* <a href="#bullet3">3 - Retrieve data</a>
    * <a href="#bullet3x1">3.1 - Connect to Sefaria</a>
    * <a href="#bullet3x2">3.2 - Search for relevant passages</a>
    * <a href="#bullet3x3">3.3 - Follow links from Deuteronomy 31:12</a>
    * <a href="#bullet3x4">3.4 - Retrieve the full texts</a>
* <a href="#bullet4">4 - Curated chronological map</a>
    * <a href="#bullet4x1">4.1 - Compare periods and themes</a>
* <a href="#bullet5">5 - Reception-history synthesis</a>
    * <a href="#bullet5x1">5.1 - The rabbinic problem is not whether children are present</a>
    * <a href="#bullet5x2">5.2 - The saying in later interpretation</a>
    * <a href="#bullet5x3">5.3 - Medieval interpreters reopen the scriptural rationale</a>
    * <a href="#bullet5x4">5.4 - Later interpreters differentiate kinds of children</a>
    * <a href="#bullet5x5">5.5 - Synagogue reception produces extension and resistance</a>
    * <a href="#bullet5x6">5.6 - Hasidic readings of what children receive</a>
    * <a href="#bullet5x7">5.7 - Modern readings of covenant renewal</a>
* <a href="#bullet6">6 - Main conclusion</a>
* <a href="#bullet7">7 - Export reproducible results</a>
    * <a href="#bullet7x1">7.1 - Check the results</a>
* <a href="#bullet8">8 - Required libraries</a>
* <a href="#bullet9">9 - Responsible disclosure</a>
* <a href="#bullet10">10 - Licences</a>
* <a href="#bullet11">11 - Notebook details</a>

# 1 - Purpose, method and limits<a class="anchor" id="bullet1"></a>
##### [Back to ToC](#TOC)

This notebook traces how Jewish interpreters received the inclusion of `הטף` (“the little ones”) in Deut 31:12. Of particular interest is the rabbinic question and answer, `טף למה באין? ... ליתן שכר למביאיהן`: why do the little ones come, and why is merit assigned to those who bring them?

The source data and the interpretive layers remain separate. Sefaria supplies search hits, links, and text. `evidence.csv` is a manually curated chronological reading table. The final discovery tags are a researcher-supplied keyword index for navigating the retrieved texts; Sefaria does not supply them.

The retrieval plan specifies the search terms and reference seeds, including Maor VaShemesh, Vayeilech 5. The notebook retrieves the texts through Sefaria and saves the results with their run metadata.

In this notebook we will use three Sefaria MCP operations:

- keyword search to discover reception witnesses;
- link retrieval from Deut 31:12 to identify direct commentary;
- full-text retrieval for close reading.

Run the cells in order to save a dated run under `results/source_runs/`. Each run contains raw responses, reading tables, and a validation audit. Search indexes and available text versions can change, so the audit forms part of the evidence.

The resulting chronology is a reception map, not a claim that Sefaria contains every relevant source. Search results should be checked against critical editions when textual variants or dating matter.

# 2 - Set up dependencies<a class="anchor" id="bullet2"></a>
##### [Back to ToC](#TOC)

The notebook needs a few Python libraries to contact Sefaria and work with the returned data. The next cell shows how to install them from the requirements file. Leave the installation line commented out when the libraries are already available.

In [1]:
# Dependencies are listed in reception_history/requirements.txt.
# Uncomment the next line only when preparing a new environment.
# %pip install -q -r "requirements.txt"

# 3 - Retrieve data<a class="anchor" id="bullet3"></a>
##### [Back to ToC](#TOC)

We first set the location of the notebook files and the Sefaria connection. The retrieval plan contains the search terms and the references to fetch. A folder named with the date and time keeps each run’s results together.

In [2]:
# Method, paths, and one fresh retrieval run
from __future__ import annotations

from datetime import datetime, timezone
from zoneinfo import ZoneInfo
import uuid
import sys
import importlib.metadata as package_metadata
import json
import re
from pathlib import Path
from typing import Any

import pandas as pd
from tqdm.auto import tqdm
from mcp import ClientSession
from mcp.client.sse import sse_client

MCP_SERVER_URL = "https://mcp.sefaria.org/sse"

HERE = Path.cwd()
if not (HERE / "results").exists() and (HERE / "reception_history").exists():
    HERE = HERE / "reception_history"
RESULTS = HERE / "results"
RESULTS.mkdir(exist_ok=True)

strategy = json.loads((HERE / "retrieval_plan.json").read_text(encoding="utf-8"))
RUN_ID = datetime.now(ZoneInfo("Europe/Amsterdam")).strftime("live_%Y-%m-%d_%H%M%S") + "_" + uuid.uuid4().hex[:8]
RUN_DIR = RESULTS / "source_runs" / RUN_ID
RUN_DIR.mkdir(parents=True, exist_ok=False)
STARTED_AT = datetime.now(ZoneInfo("Europe/Amsterdam")).isoformat()
SEARCH_QUERIES = strategy["queries"]
SEED_REFS = strategy["seed_references"]

print("Fresh retrieval:", RUN_ID)
print("Search queries:", len(SEARCH_QUERIES))

D:\Onedrive\GitHub\Hakhel\.tmp\mcp130-verified\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Fresh retrieval: live_2026-10-26_105712_58edc937
Search queries: 12

## 3.1 - Connect to Sefaria<a class="anchor" id="bullet3x1"></a>
##### [Back to ToC](#TOC)

The next cell defines the small helper functions used to contact Sefaria. They send a request, read the response, and turn it into data that Python can use. If Sefaria reports an error, the notebook shows it instead of treating it as a successful result.

In [3]:
# Handle MCP responses
def decode_result(result: Any) -> Any:
    content = getattr(result, "content", result)
    if isinstance(content, list) and content:
        content = getattr(content[0], "text", content[0])
    if isinstance(content, str):
        try:
            payload = json.loads(content)
        except json.JSONDecodeError:
            return content
        if isinstance(payload, dict) and "result" in payload:
            inner = payload["result"]
            if isinstance(inner, str):
                try:
                    return json.loads(inner)
                except json.JSONDecodeError:
                    return inner
            return inner
        return payload
    return content


async def call_tool(name: str, arguments: dict[str, Any]) -> Any:
    async with sse_client(MCP_SERVER_URL) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            result = await session.call_tool(name, arguments)
            if getattr(result, "isError", False):
                raise RuntimeError(f"Sefaria {name}: {decode_result(result)}")
            return decode_result(result)


async def list_tools() -> list[dict[str, Any]]:
    async with sse_client(MCP_SERVER_URL) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            response = await session.list_tools()
            return [tool.model_dump() for tool in response.tools]

## 3.2 - Search for relevant passages<a class="anchor" id="bullet3x2"></a>
##### [Back to ToC](#TOC)

We now run each search term in the retrieval plan. Each result keeps the term that found it, so we can trace how a passage entered the study. The raw responses are saved before repeated references are removed from the reading table. The table below shows the first results.

In [4]:
# Search for reception witnesses
def result_rows(payload: Any, query: str) -> list[dict[str, Any]]:
    """Normalize result objects while retaining their search query."""
    if isinstance(payload, dict):
        payload = payload.get("results", payload.get("hits", []))
    rows = []
    for item in payload or []:
        row = dict(item)
        row["search_query"] = query
        rows.append(row)
    return rows


raw_searches = []
rows = []
for query in tqdm(SEARCH_QUERIES, desc="Sefaria searches"):
    payload = await call_tool("text_search", {"query": query, "size": strategy["search_size"]})
    raw_searches.append({"query": query, "payload": payload})
    rows.extend(result_rows(payload, query))
    with (RUN_DIR / "raw_search_payloads.jsonl").open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(raw_searches[-1], ensure_ascii=False) + "\n")

search_df = pd.DataFrame(rows)
if not search_df.empty and "ref" in search_df:
    search_df = search_df.drop_duplicates(subset=["ref"]).reset_index(drop=True)

search_df.head(20)

Sefaria searches:   0%|          | 0/12 [00:00<?, ?it/s]

Sefaria searches:   8%|▊         | 1/12 [00:04<00:51,  4.65s/it]

Sefaria searches:  17%|█▋        | 2/12 [00:08<00:41,  4.14s/it]

Sefaria searches:  25%|██▌       | 3/12 [00:10<00:28,  3.13s/it]

Sefaria searches:  33%|███▎      | 4/12 [00:12<00:23,  2.89s/it]

Sefaria searches:  42%|████▏     | 5/12 [00:15<00:19,  2.73s/it]

Sefaria searches:  50%|█████     | 6/12 [00:16<00:13,  2.29s/it]

Sefaria searches:  58%|█████▊    | 7/12 [00:18<00:10,  2.06s/it]

Sefaria searches:  67%|██████▋   | 8/12 [00:21<00:10,  2.53s/it]

Sefaria searches:  75%|███████▌  | 9/12 [00:27<00:10,  3.37s/it]

Sefaria searches:  83%|████████▎ | 10/12 [00:28<00:05,  2.75s/it]

Sefaria searches:  92%|█████████▏| 11/12 [00:33<00:03,  3.35s/it]

Sefaria searches: 100%|██████████| 12/12 [00:35<00:00,  3.01s/it]

Sefaria searches: 100%|██████████| 12/12 [00:35<00:00,  2.95s/it]

,ref,categories,text_snippet,search_query
0,Deuteronomy 31:12,"[Tanakh, Torah]",<b>הַקְהֵל</b> <b>אֶת</b>־<b>הָעָם</b> <b>הָאֲ...,הקהל את העם האנשים והנשים והטף
1,Chagigah 3a:17,"[Talmud, Bavli, Seder Moed]",<b>הקהל</b> <b>את</b> <b>העם</b> <b>האנשים</b>...,הקהל את העם האנשים והנשים והטף
2,"Mishneh Torah, Festival Offering 3:1","[Halakhah, Mishneh Torah, Sefer Korbanot]",מִצְוַת עֲשֵׂה לְהַקְהִיל כָּל יִשְׂרָאֵל <b>א...,הקהל את העם האנשים והנשים והטף
3,Chagigah 3a:2,"[Talmud, Bavli, Seder Moed]",לְעִנְיַן רְאִיָּה גָּמַר ״רְאִיָּה״ ״רְאִיָּה...,הקהל את העם האנשים והנשים והטף
4,Sefer HaChinukh 612:1,"[Halakhah, Sifrei Mitzvot]",לְהַקְהִיל כָּל יִשְׂרָאֵל בְּחַג הַסֻּכּוֹת –...,הקהל את העם האנשים והנשים והטף
5,Jerusalem Talmud Sotah 3:4:6,"[Talmud, Yerushalmi, Seder Nashim]",וְהִקְבִילוּ <b>אֶת</b> רִבִּי יְהוֹשֻׁעַ בִּב...,הקהל את העם האנשים והנשים והטף
6,Sefer Chasidim 313:1,"[Halakhah, Rishonim]",כאלו מלמדה תיפלות זהו עומק תלמוד וטעמי המצות ו...,הקהל את העם האנשים והנשים והטף
7,Bamidbar Rabbah 14:4,"[Midrash, Aggadah, Midrash Rabbah]",עַל פִּי כֵן אִי אֶפְשָׁר לְבֵית הַמִּדְרָשׁ ב...,הקהל את העם האנשים והנשים והטף
8,Avot DeRabbi Natan 18:2,"[Talmud, Bavli, Minor Tractates]",אמר להם ובמה היתה ההגדה היום אמרו בפרשת <b>הקה...,הקהל את העם האנשים והנשים והטף
9,"Abudarham, Pesach, Festival Prayers 12","[Halakhah, Rishonim]",ועוד טעם אחר לפי שאבותינו לא קבלו <b>את</b> הת...,הקהל את העם האנשים והנשים והטף
10,Tosafot on Sotah 20a:7:1,"[Talmud Commentary, Rishonim on Talmud, Tosafo...",בן עזאי אומר חייב אדם וכו' - ירושלמי דבן עזאי ...,הקהל את העם האנשים והנשים והטף
11,Tosefta Sotah 7:6,"[Tosefta, Vilna Edition, Seder Nashim]",להם ר' יהושע מה חדוש היה בבית המדרש היום אמרו ...,הקהל את העם האנשים והנשים והטף
12,"Abarbanel on Torah, Deuteronomy 31:9:5","[Tanakh Commentary, Rishonim on Tanakh, Abarba...",וצוה <b>הקהל</b> <b>את</b> <b>העם</b> <b>האנשי...,הקהל את העם האנשים והנשים והטף
13,"Duties of the Heart, Third Treatise on Service...","[Jewish Thought, Rishonim, Duties of the Heart]",לַנַּעַר וְלַבָּחוּר וְלַיָּשִׁישׁ וְלַזָּקֵן ...,הקהל את העם האנשים והנשים והטף
14,Jerusalem Talmud Chagigah 1:1:2,"[Talmud, Yerushalmi, Seder Moed]",מתני' בראיית קרבן אבל בראיית פנים אפי' קטן חיי...,הקהל את העם האנשים והנשים והטף
15,Jerusalem Talmud Chagigah 1:1:3,"[Talmud, Yerushalmi, Seder Moed]",<b>הַקְהֵל</b> <b>אֶת</b> <b>הָעָם</b> <b>הָאֲ...,הקהל את העם האנשים והנשים והטף
16,Kli Yakar on Deuteronomy 31:12:1,"[Tanakh Commentary, Acharonim on Tanakh, Kli Y...",<b>הקהל</b> <b>את</b> <b>העם</b> <b>האנשים</b>...,הקהל את העם האנשים והנשים והטף
17,"Zohar, Vayakhel 1:9","[Kabbalah, Zohar]",<b>וַיַּקְהֵל</b> מֹשֶׁה. רִבִּי אַבָּא פָּתַח...,הקהל את העם האנשים והנשים והטף
18,"Bach, Yoreh De'ah 246:9:1","[Halakhah, Tur, Commentary]","ומ""ש שלא ילמד אדם <b>את</b> בתו תורה משנה פרק ...",הקהל את העם האנשים והנשים והטף
19,Ran on Megillah 3b:5,"[Talmud Commentary, Rishonim on Talmud, Rif, C...",<b>והקהל</b>. דכתיב <b>הקהל</b> <b>את</b> <b>ה...,הקהל את העם האנשים והנשים והטף

## 3.3 - Follow links from Deuteronomy 31:12<a class="anchor" id="bullet3x3"></a>
##### [Back to ToC](#TOC)

Keyword searches can miss a commentary that does not repeat our search terms. We therefore also ask Sefaria for the texts linked directly to Deut 31:12. The table shows the reference, the kind of link, and the category assigned by Sefaria.

In [5]:
# Retrieve links from the anchor verse
linked = await call_tool(
    "get_links_between_texts",
    {"reference": "Deuteronomy 31:12", "with_text": "1"},
)
links_df = pd.DataFrame(linked or [])

links_df[["ref", "type", "category"]].head(30)

,ref,type,category
0,Ramban on Deuteronomy 31:12:1,commentary,Commentary
1,Rashi on Deuteronomy 31:12:1,commentary,Commentary
2,Rashi on Deuteronomy 31:12:2,commentary,Commentary
3,Ibn Ezra on Deuteronomy 31:12:1,commentary,Commentary
4,Ibn Ezra on Deuteronomy 31:12:2,commentary,Commentary
5,Onkelos Deuteronomy 31:12,targum,Targum
6,Targum Jonathan on Deuteronomy 31:12,targum,Targum
7,Kli Yakar on Deuteronomy 31:12:1,commentary,Commentary
8,Kli Yakar on Deuteronomy 31:12:2,commentary,Commentary
9,Kli Yakar on Deuteronomy 31:12:3,commentary,Commentary
10,Kli Yakar on Deuteronomy 31:12:4,commentary,Commentary
11,Sforno on Deuteronomy 31:12:1,commentary,Commentary
12,Sforno on Deuteronomy 31:12:2,commentary,Commentary
13,Sforno on Deuteronomy 31:12:3,commentary,Commentary
14,Rashi on Deuteronomy 31:12:3,commentary,Commentary
15,Kitzur Ba'al HaTurim on Deuteronomy 31:12:1,commentary,Commentary
16,Or HaChaim on Deuteronomy 31:12:1,commentary,Commentary
17,"Meshekh Chokhmah, Vayelekh 10",parshanut,Quoting Commentary
18,Haamek Davar on Deuteronomy 31:12:1,commentary,Commentary
19,Haamek Davar on Deuteronomy 31:12:2,commentary,Commentary
20,Haamek Davar on Deuteronomy 31:12:3,commentary,Commentary
21,"Sefer HaMitzvot, Positive Commandments 16:1",commentary,Halakhah
22,"Penei David, Deuteronomy, Vayeilech 2:1-2",commentary,Commentary
23,"Tafsir Rasag, Deuteronomy 31:12",targum,Targum
24,"Mei HaShiloach, Volume II, Deuteronomy, Vayeil...",commentary,Chasidut
25,"Minchat Shai on Torah, Deuteronomy 31:12:1",commentary,Commentary
26,"Mizrachi, Deuteronomy 31:12:1",commentary,Commentary
27,"HaKtav VeHaKabalah, Deuteronomy 31:12:1",commentary,Commentary
28,"HaKtav VeHaKabalah, Deuteronomy 31:12:2",commentary,Commentary
29,"Torah Temimah on Torah, Deuteronomy 31:12:1",commentary,Commentary

## 3.4 - Retrieve the full texts<a class="anchor" id="bullet3x4"></a>
##### [Back to ToC](#TOC)

The next cell brings together the planned references, the search results, and the links from the verse. It retrieves each reference once and keeps the available Hebrew and English texts. Simple web formatting is removed for easier reading. Raw responses are saved separately; failed or empty responses are recorded for later review.

In [6]:
# Retrieve full texts for close reading
def strip_html(value: Any) -> str:
    if isinstance(value, list):
        return " ".join(strip_html(v) for v in value)
    return re.sub(r"<[^>]+>", "", str(value or "")).strip()


def normalize_text(ref: str, payload: Any) -> dict[str, Any]:
    """Keep the first available Hebrew and English versions."""
    versions = payload.get("versions", []) if isinstance(payload, dict) else []
    row = {"ref": payload.get("ref", ref) if isinstance(payload, dict) else ref}
    for version in versions:
        language = version.get("languageFamilyName", "").lower()
        if language == "hebrew" and "hebrew" not in row:
            row["hebrew"] = strip_html(version.get("text"))
        if language == "english" and "english" not in row:
            row["english"] = strip_html(version.get("text"))
    return row


discovered = [] if search_df.empty else search_df["ref"].dropna().tolist()
linked_refs = [] if links_df.empty else links_df["ref"].dropna().tolist()
refs = list(dict.fromkeys(SEED_REFS + discovered + linked_refs))

texts = []
for ref in tqdm(refs, desc="Full texts"):
    try:
        payload = await call_tool(
            "get_text", {"reference": ref, "version_language": "both"}
        )
        row = normalize_text(ref, payload)
        if not row.get("hebrew") and not row.get("english"):
            raise ValueError("Response contains no Hebrew or English text")
        texts.append(row)
        with (RUN_DIR / "raw_full_text_payloads.jsonl").open("a", encoding="utf-8") as handle:
            handle.write(json.dumps({"requested_ref": ref, "payload": payload}, ensure_ascii=False) + "\n")
    except Exception as exc:
        texts.append({"ref": ref, "error": repr(exc)})
texts_df = pd.DataFrame(texts)

texts_df.head(20)

Full texts:   0%|          | 0/345 [00:00<?, ?it/s]

Full texts:   0%|          | 1/345 [00:01<10:27,  1.83s/it]

Full texts:   1%|          | 2/345 [00:03<08:16,  1.45s/it]

Full texts:   1%|          | 3/345 [00:04<07:14,  1.27s/it]

Full texts:   1%|          | 4/345 [00:05<07:05,  1.25s/it]

Full texts:   1%|▏         | 5/345 [00:06<07:18,  1.29s/it]

Full texts:   2%|▏         | 6/345 [00:08<07:29,  1.33s/it]

Full texts:   2%|▏         | 7/345 [00:09<07:21,  1.31s/it]

Full texts:   2%|▏         | 8/345 [00:10<07:02,  1.25s/it]

Full texts:   3%|▎         | 9/345 [00:12<07:33,  1.35s/it]

Full texts:   3%|▎         | 10/345 [00:13<07:31,  1.35s/it]

Full texts:   3%|▎         | 11/345 [00:14<07:06,  1.28s/it]

Full texts:   3%|▎         | 12/345 [00:15<06:44,  1.21s/it]

Full texts:   4%|▍         | 13/345 [00:16<06:20,  1.15s/it]

Full texts:   4%|▍         | 14/345 [00:17<06:01,  1.09s/it]

Full texts:   4%|▍         | 15/345 [00:18<05:55,  1.08s/it]

Full texts:   5%|▍         | 16/345 [00:26<17:09,  3.13s/it]

Full texts:   5%|▍         | 17/345 [00:27<14:28,  2.65s/it]

Full texts:   5%|▌         | 18/345 [00:28<11:45,  2.16s/it]

Full texts:   6%|▌         | 19/345 [00:30<09:56,  1.83s/it]

Full texts:   6%|▌         | 20/345 [00:31<09:20,  1.72s/it]

Full texts:   6%|▌         | 21/345 [00:33<09:18,  1.72s/it]

Full texts:   6%|▋         | 22/345 [00:34<08:06,  1.51s/it]

Full texts:   7%|▋         | 23/345 [00:35<08:10,  1.52s/it]

Full texts:   7%|▋         | 24/345 [00:36<07:25,  1.39s/it]

Full texts:   7%|▋         | 25/345 [00:38<07:15,  1.36s/it]

Full texts:   8%|▊         | 26/345 [00:39<07:17,  1.37s/it]

Full texts:   8%|▊         | 27/345 [00:40<06:53,  1.30s/it]

Full texts:   8%|▊         | 28/345 [00:41<06:27,  1.22s/it]

Full texts:   8%|▊         | 29/345 [00:42<06:10,  1.17s/it]

Full texts:   9%|▊         | 30/345 [00:43<05:39,  1.08s/it]

Full texts:   9%|▉         | 31/345 [00:44<05:51,  1.12s/it]

Full texts:   9%|▉         | 32/345 [00:46<06:06,  1.17s/it]

Full texts:  10%|▉         | 33/345 [00:47<05:56,  1.14s/it]

Full texts:  10%|▉         | 34/345 [00:48<06:00,  1.16s/it]

Full texts:  10%|█         | 35/345 [00:49<05:40,  1.10s/it]

Full texts:  10%|█         | 36/345 [00:50<05:37,  1.09s/it]

Full texts:  11%|█         | 37/345 [00:54<10:04,  1.96s/it]

Full texts:  11%|█         | 38/345 [00:55<09:18,  1.82s/it]

Full texts:  11%|█▏        | 39/345 [00:58<10:01,  1.97s/it]

Full texts:  12%|█▏        | 40/345 [00:59<08:34,  1.69s/it]

Full texts:  12%|█▏        | 41/345 [01:00<07:44,  1.53s/it]

Full texts:  12%|█▏        | 42/345 [01:01<07:16,  1.44s/it]

Full texts:  12%|█▏        | 43/345 [01:02<06:44,  1.34s/it]

Full texts:  13%|█▎        | 44/345 [01:03<06:01,  1.20s/it]

Full texts:  13%|█▎        | 45/345 [01:04<05:29,  1.10s/it]

Full texts:  13%|█▎        | 46/345 [01:05<05:28,  1.10s/it]

Full texts:  14%|█▎        | 47/345 [01:06<05:35,  1.13s/it]

Full texts:  14%|█▍        | 48/345 [01:08<05:46,  1.17s/it]

Full texts:  14%|█▍        | 49/345 [01:09<05:36,  1.14s/it]

Full texts:  14%|█▍        | 50/345 [01:10<05:33,  1.13s/it]

Full texts:  15%|█▍        | 51/345 [01:11<05:30,  1.13s/it]

Full texts:  15%|█▌        | 52/345 [01:12<05:58,  1.22s/it]

Full texts:  15%|█▌        | 53/345 [01:13<05:21,  1.10s/it]

Full texts:  16%|█▌        | 54/345 [01:14<05:26,  1.12s/it]

Full texts:  16%|█▌        | 55/345 [01:16<05:41,  1.18s/it]

Full texts:  16%|█▌        | 56/345 [01:16<05:09,  1.07s/it]

Full texts:  17%|█▋        | 57/345 [01:18<05:29,  1.14s/it]

Full texts:  17%|█▋        | 58/345 [01:19<05:36,  1.17s/it]

Full texts:  17%|█▋        | 59/345 [01:20<05:08,  1.08s/it]

Full texts:  17%|█▋        | 60/345 [01:21<05:17,  1.12s/it]

Full texts:  18%|█▊        | 61/345 [01:22<05:08,  1.09s/it]

Full texts:  18%|█▊        | 62/345 [01:23<05:06,  1.08s/it]

Full texts:  18%|█▊        | 63/345 [01:24<05:07,  1.09s/it]

Full texts:  19%|█▊        | 64/345 [01:25<05:03,  1.08s/it]

Full texts:  19%|█▉        | 65/345 [01:27<05:27,  1.17s/it]

Full texts:  19%|█▉        | 66/345 [01:28<05:48,  1.25s/it]

Full texts:  19%|█▉        | 67/345 [01:30<06:13,  1.34s/it]

Full texts:  20%|█▉        | 68/345 [01:31<05:57,  1.29s/it]

Full texts:  20%|██        | 69/345 [01:32<05:19,  1.16s/it]

Full texts:  20%|██        | 70/345 [01:33<04:54,  1.07s/it]

Full texts:  21%|██        | 71/345 [01:34<04:57,  1.09s/it]

Full texts:  21%|██        | 72/345 [01:35<04:54,  1.08s/it]

Full texts:  21%|██        | 73/345 [01:36<05:15,  1.16s/it]

Full texts:  21%|██▏       | 74/345 [01:37<05:32,  1.23s/it]

Full texts:  22%|██▏       | 75/345 [01:39<05:27,  1.21s/it]

Full texts:  22%|██▏       | 76/345 [01:40<05:28,  1.22s/it]

Full texts:  22%|██▏       | 77/345 [01:41<05:24,  1.21s/it]

Full texts:  23%|██▎       | 78/345 [01:42<04:54,  1.10s/it]

Full texts:  23%|██▎       | 79/345 [01:43<04:59,  1.13s/it]

Full texts:  23%|██▎       | 80/345 [01:44<04:57,  1.12s/it]

Full texts:  23%|██▎       | 81/345 [01:45<04:59,  1.13s/it]

Full texts:  24%|██▍       | 82/345 [01:46<04:38,  1.06s/it]

Full texts:  24%|██▍       | 83/345 [01:47<04:18,  1.02it/s]

Full texts:  24%|██▍       | 84/345 [01:48<04:43,  1.09s/it]

Full texts:  25%|██▍       | 85/345 [01:49<04:41,  1.08s/it]

Full texts:  25%|██▍       | 86/345 [01:51<04:38,  1.08s/it]

Full texts:  25%|██▌       | 87/345 [01:52<05:02,  1.17s/it]

Full texts:  26%|██▌       | 88/345 [01:53<04:49,  1.13s/it]

Full texts:  26%|██▌       | 89/345 [01:54<04:42,  1.10s/it]

Full texts:  26%|██▌       | 90/345 [01:55<04:52,  1.15s/it]

Full texts:  26%|██▋       | 91/345 [01:57<05:01,  1.19s/it]

Full texts:  27%|██▋       | 92/345 [01:58<04:47,  1.14s/it]

Full texts:  27%|██▋       | 93/345 [01:58<04:21,  1.04s/it]

Full texts:  27%|██▋       | 94/345 [01:59<04:17,  1.03s/it]

Full texts:  28%|██▊       | 95/345 [02:00<04:22,  1.05s/it]

Full texts:  28%|██▊       | 96/345 [02:02<04:26,  1.07s/it]

Full texts:  28%|██▊       | 97/345 [02:02<04:10,  1.01s/it]

Full texts:  28%|██▊       | 98/345 [02:04<04:17,  1.04s/it]

Full texts:  29%|██▊       | 99/345 [02:05<04:38,  1.13s/it]

Full texts:  29%|██▉       | 100/345 [02:06<04:37,  1.13s/it]

Full texts:  29%|██▉       | 101/345 [02:08<05:01,  1.24s/it]

Full texts:  30%|██▉       | 102/345 [02:09<05:12,  1.29s/it]

Full texts:  30%|██▉       | 103/345 [02:10<05:26,  1.35s/it]

Full texts:  30%|███       | 104/345 [02:12<05:15,  1.31s/it]

Full texts:  30%|███       | 105/345 [02:13<05:29,  1.37s/it]

Full texts:  31%|███       | 106/345 [02:14<05:13,  1.31s/it]

Full texts:  31%|███       | 107/345 [02:16<05:02,  1.27s/it]

Full texts:  31%|███▏      | 108/345 [02:17<05:18,  1.34s/it]

Full texts:  32%|███▏      | 109/345 [02:18<04:50,  1.23s/it]

Full texts:  32%|███▏      | 110/345 [02:19<05:06,  1.31s/it]

Full texts:  32%|███▏      | 111/345 [02:21<04:54,  1.26s/it]

Full texts:  32%|███▏      | 112/345 [02:22<04:50,  1.25s/it]

Full texts:  33%|███▎      | 113/345 [02:23<05:04,  1.31s/it]

Full texts:  33%|███▎      | 114/345 [02:24<04:35,  1.19s/it]

Full texts:  33%|███▎      | 115/345 [02:25<04:20,  1.13s/it]

Full texts:  34%|███▎      | 116/345 [02:27<04:38,  1.22s/it]

Full texts:  34%|███▍      | 117/345 [02:28<04:25,  1.17s/it]

Full texts:  34%|███▍      | 118/345 [02:29<05:04,  1.34s/it]

Full texts:  34%|███▍      | 119/345 [02:31<05:07,  1.36s/it]

Full texts:  35%|███▍      | 120/345 [02:32<05:11,  1.38s/it]

Full texts:  35%|███▌      | 121/345 [02:33<04:57,  1.33s/it]

Full texts:  35%|███▌      | 122/345 [02:35<04:46,  1.28s/it]

Full texts:  36%|███▌      | 123/345 [02:36<04:46,  1.29s/it]

Full texts:  36%|███▌      | 124/345 [02:37<04:54,  1.33s/it]

Full texts:  36%|███▌      | 125/345 [02:39<04:41,  1.28s/it]

Full texts:  37%|███▋      | 126/345 [02:40<04:53,  1.34s/it]

Full texts:  37%|███▋      | 127/345 [02:41<04:45,  1.31s/it]

Full texts:  37%|███▋      | 128/345 [02:42<04:17,  1.19s/it]

Full texts:  37%|███▋      | 129/345 [02:44<04:33,  1.27s/it]

Full texts:  38%|███▊      | 130/345 [02:45<04:22,  1.22s/it]

Full texts:  38%|███▊      | 131/345 [02:46<04:19,  1.21s/it]

Full texts:  38%|███▊      | 132/345 [02:47<04:31,  1.27s/it]

Full texts:  39%|███▊      | 133/345 [02:49<04:47,  1.36s/it]

Full texts:  39%|███▉      | 134/345 [02:50<04:45,  1.35s/it]

Full texts:  39%|███▉      | 135/345 [02:51<04:32,  1.30s/it]

Full texts:  39%|███▉      | 136/345 [02:53<04:31,  1.30s/it]

Full texts:  40%|███▉      | 137/345 [02:54<04:25,  1.28s/it]

Full texts:  40%|████      | 138/345 [02:55<04:16,  1.24s/it]

Full texts:  40%|████      | 139/345 [02:56<04:08,  1.20s/it]

Full texts:  41%|████      | 140/345 [02:57<04:11,  1.22s/it]

Full texts:  41%|████      | 141/345 [02:59<04:24,  1.30s/it]

Full texts:  41%|████      | 142/345 [03:00<04:14,  1.25s/it]

Full texts:  41%|████▏     | 143/345 [03:02<04:26,  1.32s/it]

Full texts:  42%|████▏     | 144/345 [03:02<03:59,  1.19s/it]

Full texts:  42%|████▏     | 145/345 [03:04<03:56,  1.18s/it]

Full texts:  42%|████▏     | 146/345 [03:05<03:54,  1.18s/it]

Full texts:  43%|████▎     | 147/345 [03:06<03:35,  1.09s/it]

Full texts:  43%|████▎     | 148/345 [03:07<03:32,  1.08s/it]

Full texts:  43%|████▎     | 149/345 [03:08<03:32,  1.08s/it]

Full texts:  43%|████▎     | 150/345 [03:09<03:42,  1.14s/it]

Full texts:  44%|████▍     | 151/345 [03:10<03:49,  1.18s/it]

Full texts:  44%|████▍     | 152/345 [03:12<04:10,  1.30s/it]

Full texts:  44%|████▍     | 153/345 [03:13<04:10,  1.31s/it]

Full texts:  45%|████▍     | 154/345 [03:14<03:51,  1.21s/it]

Full texts:  45%|████▍     | 155/345 [03:16<03:58,  1.25s/it]

Full texts:  45%|████▌     | 156/345 [03:17<03:49,  1.22s/it]

Full texts:  46%|████▌     | 157/345 [03:18<03:49,  1.22s/it]

Full texts:  46%|████▌     | 158/345 [03:19<03:53,  1.25s/it]

Full texts:  46%|████▌     | 159/345 [03:20<03:35,  1.16s/it]

Full texts:  46%|████▋     | 160/345 [03:21<03:37,  1.18s/it]

Full texts:  47%|████▋     | 161/345 [03:22<03:21,  1.09s/it]

Full texts:  47%|████▋     | 162/345 [03:23<03:21,  1.10s/it]

Full texts:  47%|████▋     | 163/345 [03:25<03:30,  1.16s/it]

Full texts:  48%|████▊     | 164/345 [03:26<03:38,  1.21s/it]

Full texts:  48%|████▊     | 165/345 [03:27<03:26,  1.15s/it]

Full texts:  48%|████▊     | 166/345 [03:28<03:13,  1.08s/it]

Full texts:  48%|████▊     | 167/345 [03:29<03:08,  1.06s/it]

Full texts:  49%|████▊     | 168/345 [03:30<03:20,  1.13s/it]

Full texts:  49%|████▉     | 169/345 [03:31<03:13,  1.10s/it]

Full texts:  49%|████▉     | 170/345 [03:33<03:25,  1.17s/it]

Full texts:  50%|████▉     | 171/345 [03:34<03:37,  1.25s/it]

Full texts:  50%|████▉     | 172/345 [03:35<03:31,  1.22s/it]

Full texts:  50%|█████     | 173/345 [03:37<03:38,  1.27s/it]

Full texts:  50%|█████     | 174/345 [03:38<03:24,  1.20s/it]

Full texts:  51%|█████     | 175/345 [03:39<03:19,  1.17s/it]

Full texts:  51%|█████     | 176/345 [03:40<03:16,  1.16s/it]

Full texts:  51%|█████▏    | 177/345 [03:41<03:18,  1.18s/it]

Full texts:  52%|█████▏    | 178/345 [03:42<03:06,  1.12s/it]

Full texts:  52%|█████▏    | 179/345 [03:44<03:41,  1.34s/it]

Full texts:  52%|█████▏    | 180/345 [03:49<06:57,  2.53s/it]

Full texts:  52%|█████▏    | 181/345 [03:51<06:01,  2.21s/it]

Full texts:  53%|█████▎    | 182/345 [03:52<04:51,  1.79s/it]

Full texts:  53%|█████▎    | 183/345 [03:52<04:05,  1.52s/it]

Full texts:  53%|█████▎    | 184/345 [03:53<03:28,  1.30s/it]

Full texts:  54%|█████▎    | 185/345 [03:54<03:24,  1.28s/it]

Full texts:  54%|█████▍    | 186/345 [03:56<03:26,  1.30s/it]

Full texts:  54%|█████▍    | 187/345 [03:57<03:13,  1.22s/it]

Full texts:  54%|█████▍    | 188/345 [03:58<02:54,  1.11s/it]

Full texts:  55%|█████▍    | 189/345 [03:59<02:46,  1.07s/it]

Full texts:  55%|█████▌    | 190/345 [04:00<02:44,  1.06s/it]

Full texts:  55%|█████▌    | 191/345 [04:01<02:39,  1.03s/it]

Full texts:  56%|█████▌    | 192/345 [04:02<02:37,  1.03s/it]

Full texts:  56%|█████▌    | 193/345 [04:03<02:38,  1.04s/it]

Full texts:  56%|█████▌    | 194/345 [04:05<03:11,  1.27s/it]

Full texts:  57%|█████▋    | 195/345 [04:06<02:59,  1.20s/it]

Full texts:  57%|█████▋    | 196/345 [04:07<03:03,  1.23s/it]

Full texts:  57%|█████▋    | 197/345 [04:09<03:30,  1.42s/it]

Full texts:  57%|█████▋    | 198/345 [04:10<03:28,  1.42s/it]

Full texts:  58%|█████▊    | 199/345 [04:11<03:10,  1.30s/it]

Full texts:  58%|█████▊    | 200/345 [04:12<03:04,  1.27s/it]

Full texts:  58%|█████▊    | 201/345 [04:13<02:52,  1.20s/it]

Full texts:  59%|█████▊    | 202/345 [04:15<02:56,  1.24s/it]

Full texts:  59%|█████▉    | 203/345 [04:16<02:54,  1.23s/it]

Full texts:  59%|█████▉    | 204/345 [04:17<02:59,  1.27s/it]

Full texts:  59%|█████▉    | 205/345 [04:18<02:40,  1.14s/it]

Full texts:  60%|█████▉    | 206/345 [04:19<02:34,  1.11s/it]

Full texts:  60%|██████    | 207/345 [04:20<02:35,  1.13s/it]

Full texts:  60%|██████    | 208/345 [04:21<02:30,  1.10s/it]

Full texts:  61%|██████    | 209/345 [04:23<02:44,  1.21s/it]

Full texts:  61%|██████    | 210/345 [04:24<02:32,  1.13s/it]

Full texts:  61%|██████    | 211/345 [04:25<02:32,  1.14s/it]

Full texts:  61%|██████▏   | 212/345 [04:28<03:32,  1.60s/it]

Full texts:  62%|██████▏   | 213/345 [04:29<03:27,  1.57s/it]

Full texts:  62%|██████▏   | 214/345 [04:31<03:19,  1.52s/it]

Full texts:  62%|██████▏   | 215/345 [04:32<02:55,  1.35s/it]

Full texts:  63%|██████▎   | 216/345 [04:32<02:37,  1.22s/it]

Full texts:  63%|██████▎   | 217/345 [04:34<02:38,  1.24s/it]

Full texts:  63%|██████▎   | 218/345 [04:35<02:34,  1.22s/it]

Full texts:  63%|██████▎   | 219/345 [04:36<02:29,  1.19s/it]

Full texts:  64%|██████▍   | 220/345 [04:37<02:22,  1.14s/it]

Full texts:  64%|██████▍   | 221/345 [04:38<02:14,  1.08s/it]

Full texts:  64%|██████▍   | 222/345 [04:40<02:27,  1.20s/it]

Full texts:  65%|██████▍   | 223/345 [04:41<02:33,  1.26s/it]

Full texts:  65%|██████▍   | 224/345 [04:42<02:34,  1.28s/it]

Full texts:  65%|██████▌   | 225/345 [04:43<02:21,  1.18s/it]

Full texts:  66%|██████▌   | 226/345 [04:44<02:20,  1.18s/it]

Full texts:  66%|██████▌   | 227/345 [04:45<02:10,  1.10s/it]

Full texts:  66%|██████▌   | 228/345 [04:46<02:05,  1.07s/it]

Full texts:  66%|██████▋   | 229/345 [04:48<02:30,  1.30s/it]

Full texts:  67%|██████▋   | 230/345 [04:49<02:16,  1.18s/it]

Full texts:  67%|██████▋   | 231/345 [04:51<02:34,  1.36s/it]

Full texts:  67%|██████▋   | 232/345 [04:52<02:27,  1.30s/it]

Full texts:  68%|██████▊   | 233/345 [04:54<02:43,  1.46s/it]

Full texts:  68%|██████▊   | 234/345 [04:55<02:26,  1.32s/it]

Full texts:  68%|██████▊   | 235/345 [04:56<02:23,  1.30s/it]

Full texts:  68%|██████▊   | 236/345 [04:57<02:17,  1.26s/it]

Full texts:  69%|██████▊   | 237/345 [04:58<02:14,  1.25s/it]

Full texts:  69%|██████▉   | 238/345 [05:00<02:10,  1.22s/it]

Full texts:  69%|██████▉   | 239/345 [05:01<02:04,  1.18s/it]

Full texts:  70%|██████▉   | 240/345 [05:02<01:59,  1.14s/it]

Full texts:  70%|██████▉   | 241/345 [05:03<01:54,  1.10s/it]

Full texts:  70%|███████   | 242/345 [05:04<01:55,  1.12s/it]

Full texts:  70%|███████   | 243/345 [05:05<01:56,  1.14s/it]

Full texts:  71%|███████   | 244/345 [05:06<01:50,  1.10s/it]

Full texts:  71%|███████   | 245/345 [05:08<02:00,  1.20s/it]

Full texts:  71%|███████▏  | 246/345 [05:09<02:04,  1.26s/it]

Full texts:  72%|███████▏  | 247/345 [05:10<02:05,  1.28s/it]

Full texts:  72%|███████▏  | 248/345 [05:14<03:12,  1.99s/it]

Full texts:  72%|███████▏  | 249/345 [05:15<02:44,  1.71s/it]

Full texts:  72%|███████▏  | 250/345 [05:17<02:43,  1.72s/it]

Full texts:  73%|███████▎  | 251/345 [05:18<02:23,  1.53s/it]

Full texts:  73%|███████▎  | 252/345 [05:19<02:21,  1.53s/it]

Full texts:  73%|███████▎  | 253/345 [05:21<02:20,  1.52s/it]

Full texts:  74%|███████▎  | 254/345 [05:22<02:17,  1.51s/it]

Full texts:  74%|███████▍  | 255/345 [05:24<02:31,  1.68s/it]

Full texts:  74%|███████▍  | 256/345 [05:25<02:14,  1.52s/it]

Full texts:  74%|███████▍  | 257/345 [05:27<02:00,  1.37s/it]

Full texts:  75%|███████▍  | 258/345 [05:28<01:55,  1.32s/it]

Full texts:  75%|███████▌  | 259/345 [05:29<01:56,  1.35s/it]

Full texts:  75%|███████▌  | 260/345 [05:30<01:43,  1.22s/it]

Full texts:  76%|███████▌  | 261/345 [05:34<02:38,  1.89s/it]

Full texts:  76%|███████▌  | 262/345 [05:36<02:51,  2.06s/it]

Full texts:  76%|███████▌  | 263/345 [05:37<02:25,  1.78s/it]

Full texts:  77%|███████▋  | 264/345 [05:38<02:10,  1.61s/it]

Full texts:  77%|███████▋  | 265/345 [05:39<01:58,  1.48s/it]

Full texts:  77%|███████▋  | 266/345 [05:41<01:51,  1.41s/it]

Full texts:  77%|███████▋  | 267/345 [05:42<01:47,  1.38s/it]

Full texts:  78%|███████▊  | 268/345 [05:43<01:38,  1.28s/it]

Full texts:  78%|███████▊  | 269/345 [05:44<01:38,  1.29s/it]

Full texts:  78%|███████▊  | 270/345 [05:45<01:28,  1.17s/it]

Full texts:  79%|███████▊  | 271/345 [05:47<01:28,  1.20s/it]

Full texts:  79%|███████▉  | 272/345 [05:48<01:23,  1.15s/it]

Full texts:  79%|███████▉  | 273/345 [05:49<01:23,  1.16s/it]

Full texts:  79%|███████▉  | 274/345 [05:50<01:21,  1.15s/it]

Full texts:  80%|███████▉  | 275/345 [05:51<01:20,  1.15s/it]

Full texts:  80%|████████  | 276/345 [05:52<01:17,  1.12s/it]

Full texts:  80%|████████  | 277/345 [05:53<01:21,  1.20s/it]

Full texts:  81%|████████  | 278/345 [05:54<01:16,  1.14s/it]

Full texts:  81%|████████  | 279/345 [05:56<01:18,  1.18s/it]

Full texts:  81%|████████  | 280/345 [05:57<01:18,  1.21s/it]

Full texts:  81%|████████▏ | 281/345 [05:58<01:18,  1.22s/it]

Full texts:  82%|████████▏ | 282/345 [05:59<01:13,  1.16s/it]

Full texts:  82%|████████▏ | 283/345 [06:01<01:12,  1.18s/it]

Full texts:  82%|████████▏ | 284/345 [06:02<01:08,  1.13s/it]

Full texts:  83%|████████▎ | 285/345 [06:03<01:05,  1.09s/it]

Full texts:  83%|████████▎ | 286/345 [06:04<01:06,  1.12s/it]

Full texts:  83%|████████▎ | 287/345 [06:05<01:11,  1.23s/it]

Full texts:  83%|████████▎ | 288/345 [06:06<01:05,  1.15s/it]

Full texts:  84%|████████▍ | 289/345 [06:07<01:05,  1.17s/it]

Full texts:  84%|████████▍ | 290/345 [06:09<01:08,  1.24s/it]

Full texts:  84%|████████▍ | 291/345 [06:10<01:08,  1.26s/it]

Full texts:  85%|████████▍ | 292/345 [06:11<01:03,  1.19s/it]

Full texts:  85%|████████▍ | 293/345 [06:12<01:03,  1.22s/it]

Full texts:  85%|████████▌ | 294/345 [06:13<00:59,  1.17s/it]

Full texts:  86%|████████▌ | 295/345 [06:14<00:55,  1.10s/it]

Full texts:  86%|████████▌ | 296/345 [06:16<00:56,  1.15s/it]

Full texts:  86%|████████▌ | 297/345 [06:17<00:59,  1.24s/it]

Full texts:  86%|████████▋ | 298/345 [06:18<00:52,  1.11s/it]

Full texts:  87%|████████▋ | 299/345 [06:19<00:52,  1.15s/it]

Full texts:  87%|████████▋ | 300/345 [06:20<00:53,  1.19s/it]

Full texts:  87%|████████▋ | 301/345 [06:22<00:53,  1.21s/it]

Full texts:  88%|████████▊ | 302/345 [06:23<00:53,  1.24s/it]

Full texts:  88%|████████▊ | 303/345 [06:24<00:46,  1.12s/it]

Full texts:  88%|████████▊ | 304/345 [06:25<00:48,  1.19s/it]

Full texts:  88%|████████▊ | 305/345 [06:27<00:49,  1.24s/it]

Full texts:  89%|████████▊ | 306/345 [06:28<00:52,  1.33s/it]

Full texts:  89%|████████▉ | 307/345 [06:29<00:47,  1.24s/it]

Full texts:  89%|████████▉ | 308/345 [06:30<00:43,  1.19s/it]

Full texts:  90%|████████▉ | 309/345 [06:31<00:39,  1.09s/it]

Full texts:  90%|████████▉ | 310/345 [06:32<00:39,  1.13s/it]

Full texts:  90%|█████████ | 311/345 [06:33<00:37,  1.10s/it]

Full texts:  90%|█████████ | 312/345 [06:34<00:34,  1.04s/it]

Full texts:  91%|█████████ | 313/345 [06:35<00:31,  1.02it/s]

Full texts:  91%|█████████ | 314/345 [06:36<00:32,  1.04s/it]

Full texts:  91%|█████████▏| 315/345 [06:38<00:38,  1.30s/it]

Full texts:  92%|█████████▏| 316/345 [06:40<00:44,  1.54s/it]

Full texts:  92%|█████████▏| 317/345 [06:41<00:38,  1.38s/it]

Full texts:  92%|█████████▏| 318/345 [06:42<00:34,  1.29s/it]

Full texts:  92%|█████████▏| 319/345 [06:44<00:33,  1.31s/it]

Full texts:  93%|█████████▎| 320/345 [06:45<00:32,  1.29s/it]

Full texts:  93%|█████████▎| 321/345 [06:46<00:29,  1.21s/it]

Full texts:  93%|█████████▎| 322/345 [06:47<00:25,  1.10s/it]

Full texts:  94%|█████████▎| 323/345 [06:48<00:26,  1.20s/it]

Full texts:  94%|█████████▍| 324/345 [06:50<00:26,  1.28s/it]

Full texts:  94%|█████████▍| 325/345 [06:51<00:24,  1.21s/it]

Full texts:  94%|█████████▍| 326/345 [06:53<00:27,  1.44s/it]

Full texts:  95%|█████████▍| 327/345 [06:54<00:25,  1.39s/it]

Full texts:  95%|█████████▌| 328/345 [06:55<00:23,  1.41s/it]

Full texts:  95%|█████████▌| 329/345 [06:57<00:21,  1.37s/it]

Full texts:  96%|█████████▌| 330/345 [06:58<00:20,  1.35s/it]

Full texts:  96%|█████████▌| 331/345 [06:59<00:18,  1.32s/it]

Full texts:  96%|█████████▌| 332/345 [07:02<00:21,  1.68s/it]

Full texts:  97%|█████████▋| 333/345 [07:03<00:18,  1.55s/it]

Full texts:  97%|█████████▋| 334/345 [07:04<00:15,  1.45s/it]

Full texts:  97%|█████████▋| 335/345 [07:05<00:12,  1.26s/it]

Full texts:  97%|█████████▋| 336/345 [07:06<00:10,  1.15s/it]

Full texts:  98%|█████████▊| 337/345 [07:08<00:10,  1.31s/it]

Full texts:  98%|█████████▊| 338/345 [07:09<00:08,  1.26s/it]

Full texts:  98%|█████████▊| 339/345 [07:10<00:07,  1.21s/it]

Full texts:  99%|█████████▊| 340/345 [07:12<00:07,  1.42s/it]

Full texts:  99%|█████████▉| 341/345 [07:13<00:05,  1.33s/it]

Full texts:  99%|█████████▉| 342/345 [07:14<00:03,  1.29s/it]

Full texts:  99%|█████████▉| 343/345 [07:15<00:02,  1.23s/it]

Full texts: 100%|█████████▉| 344/345 [07:17<00:01,  1.40s/it]

Full texts: 100%|██████████| 345/345 [07:19<00:00,  1.60s/it]

Full texts: 100%|██████████| 345/345 [07:19<00:00,  1.27s/it]

,ref,english,hebrew,error
0,Deuteronomy 31:10-13,And Moses instructed them as follows: Every se...,וַיְצַ֥ו מֹשֶׁ֖ה אוֹתָ֣ם לֵאמֹ֑ר מִקֵּ֣ץ&thins...,NaN
1,Tosefta Sotah 7:6,It so happened with Rabbi Yochanan ben Berokah...,מעשה בר' יוחנן בן ברוקה ור' אלעזר &lt;בן&gt; ח...,NaN
2,Jerusalem Talmud Chagigah 1:1:3,"7The same text is in Soṭah3:4 (Notes 107–109, ...",דְּתַנֵּי. מַעֲשֶׂה בְרִבִּי יוֹחָנַן בֶּן בְּ...,NaN
3,Chagigah 3a:17,They said to him that Rabbi Elazar ben Azarya ...,״הַקְהֵל אֶת הָעָם הָאֲנָשִׁים וְהַנָּשִׁים וְ...,NaN
4,Mishnah Sotah 7:8,How is the portion of the Torah that is read b...,פָּרָשַׁת הַמֶּלֶךְ כֵּיצַד. מוֹצָאֵי יוֹם טוֹ...,NaN
5,"Mishneh Torah, Festival Offering 3",It is a positive commandment to gather togethe...,מִצְוַת עֲשֵׂה לְהַקְהִיל כָּל יִשְׂרָאֵל אֲנָ...,NaN
6,Rashi on Deuteronomy 31:12,"האנשים [ASSEMBLE THE PEOPLE,] MEN [WOMEN, AND ...",האנשים. לִלְמֹד: והנשים. לִשְׁמֹעַ: והטף. לָמּ...,NaN
7,"Abarbanel on Torah, Deuteronomy 31:9:5",NaN,וצוה הקהל את העם האנשים והנשים והטף. והנראה כד...,NaN
8,Kli Yakar on Deuteronomy 31:12,"Gather the people, the men, and the women, and...",הַקְהֵל אֶת הָעָם הָאֲנָשִׁים וְהַנָּשִׁים וְה...,NaN
9,"Sefat Emet, Deuteronomy, Vayeilech 3:2",The Gemara (Chagigah 3a) explains that childre...,"טף למה באין לתת שכר למביאיהן. וקשה ממ""נ אי אין...",NaN
10,"A Dictionary of the Talmud, טָפֵל",NaN,"טָפֵל ת׳ 1) שאינו עיקר, לאו דוקא of secondary...",NaN
11,"Abudarham, Pesach, Festival Prayers 12",People are accustomed to reading the Song of S...,נהגו העולם לקרות בחג המצות שיר השירים מפני שהו...,NaN
12,"Abudarham, Third Gate; Blessings on Commandmen...",But women are obligated to perform all negativ...,והנשים חייבות בכל מצות לא תעשה שהאשה הוקשה לאי...,NaN
13,"Aderet Eliyahu (Rabbi Yosef Chaim), Vayeilech 1",NaN,ויצו משה אותם לאמר מקץ שבע שנים במועד שנת השמט...,NaN
14,"Agra DeKala, Ki Tavo 6",NaN,"היום הזה י""י אלקיך מצוך לעשות את החוקים האלה ו...",NaN
15,Avot DeRabbi Natan 18:2,"When R. Joshua was an old man, his disciples c...",לעת זקנתו של ר׳ יהושע נכנסו תלמידיו לבקרו אמר ...,NaN
16,B'Mareh HaBazak Volume VII 71:6,NaN,"בימינו3כך מקובלנו מפי הכהן הגדול מאחיו, בעל ה""...",NaN
17,"BDB, גֵּר 1","גֵּר92 n.m. Ex 12:48 sojourner (Arabic جَارٌ,...",NaN,NaN
18,"BDB, טַף² 1",טַף42 n.m. coll. children (as going with quic...,NaN,NaN
19,"BDB, יָרֵא 1","† יָרֵא vb. fear (NH id.; Assyrian îrû, id.; ...",NaN,NaN

# 4 - Curated chronological map<a class="anchor" id="bullet4"></a>
##### [Back to ToC](#TOC)

The retrieved texts provide the source material. The table below is the close-reading layer: selected witnesses are ordered by period and grouped by their main interpretive theme. It reads the existing `evidence.csv` file. The categories, chronology, and descriptions are AI assisted and researcher-reviewed, and remain open to revision.

In [7]:
# Curated chronological map
evidence = pd.read_csv(RESULTS / "evidence.csv")
evidence

,period,date_range,reference,genre,reception_move,role_of_the_little_ones,theme
0,Biblical base,textual starting point,Deuteronomy 31:10-13,Torah,Commands a septennial public Torah reading bef...,They are explicitly present and 31:13 associat...,covenant inclusion
1,Early rabbinic,2nd-3rd c.,Tosefta Sotah 7:6,Tosefta,Frames the inclusion as a deliberate exegetica...,Their attendance produces reward for those who...,reward to bringers
2,Early rabbinic,3rd-6th c.,Jerusalem Talmud Chagigah 1:1:3,Yerushalmi,Transmits the Elazar ben Azariah interpretatio...,Their presence merits the adults who bring them.,reward to bringers
3,Early rabbinic,3rd-6th c.,Jerusalem Talmud Chagigah 1:1:2,Yerushalmi,Uses Hakhel to argue that a minor can be oblig...,The category טף becomes a legal analogy for mi...,minor obligation
4,Early rabbinic,3rd-6th c.,Chagigah 3a:17,Bavli,Canonizes the question and answer and calls th...,They come so reward may be given to those who ...,reward to bringers
5,Early rabbinic,3rd-7th c.,Avot DeRabbi Natan 18:2,Minor tractate,Retells the study-house narrative and preserve...,Their attendance rewards their bringers.,reward to bringers
6,Early rabbinic,late antique/early medieval,Tractate Soferim 18:6,Minor tractate,Extends the Hakhel saying into synagogue custo...,Attendance habituates children and rewards bot...,synagogue formation
7,Targumic,late antique/medieval,Targum Jonathan on Deuteronomy 31:12,Targum,Builds the rabbinic differentiation directly i...,Children share in the benefit or reward of tho...,translation as interpretation
8,Medieval,11th c.,Rashi on Deuteronomy 31:12,Biblical commentary,Makes the Bavli's three-part division the defa...,They are present to bring merit to those who c...,reward to bringers
9,Medieval,12th c.,Ibn Ezra on Deuteronomy 31:12:3,Biblical commentary,Reads hearing as the trigger for questioning a...,Young children can learn through hearing and a...,child learning
10,Medieval,13th c.,Ramban on Deuteronomy 31:12:1,Biblical commentary,Applies hearing and learning to men and women ...,The little ones remain included in the assembl...,inclusive hearing
11,Medieval,12th c.,"Mishneh Torah, Festival Offering 3",Legal code,Codifies Hakhel as a positive commandment for ...,Children belong to the legally summoned totali...,Sinai reenactment
12,Medieval,13th c.,Sefer HaChinukh 612:1,Commandment catalogue,Defines Hakhel as a national act that fixes To...,Children participate in a formative public rit...,formation
13,Late medieval,15th c.,"Abarbanel on Torah, Deuteronomy 31:9:5",Biblical commentary,Explicitly challenges the reward-only explanat...,Children hear so that they can learn fear of G...,child learning
14,Early modern,16th c.,Kli Yakar on Deuteronomy 31:12,Biblical commentary,Distinguishes children below educational age f...,Very young children merit their bringers; educ...,age differentiation
15,Early modern,17th c.,"Shenei Luchot HaBerit, Aseret HaDibrot, Tamid,...",Musar,Reverses the reward motif when uncontrolled ch...,Bringing children is praiseworthy only when th...,counter-reception
16,Modern halakhic,19th c.,Minchat Chinukh 612:1:1,Halakhic analysis,Asks for the lower age boundary of טף and dist...,Even infants beyond doubtful viability may fal...,age threshold
17,Hasidic,19th c.,"Sefat Emet, Deuteronomy, Vayeilech 3:2",Hasidic commentary,Rejects the premise that children receive no b...,Children receive an inward spiritual illuminat...,spiritual imprint
18,Hasidic,19th c.,"Maor VaShemesh, Vayeilech 5",Hasidic commentary,Reads the assembly as an act of love and unity...,Children participate in the communal unity tha...,communal solidarity
19,Modern,20th-21st c.,Covenant and Conversation; Deuteronomy; Renewa...,Modern Jewish thought,Presents Hakhel as a periodic national covenan...,Children are full members of the intergenerati...,covenant renewal

## 4.1 - Compare periods and themes<a class="anchor" id="bullet4x1"></a>
##### [Back to ToC](#TOC)

This table counts the selected witnesses for each combination of period and theme. It helps us see how the curated examples are distributed. These counts describe our selection; they do not measure how common a reading was in Jewish interpretation as a whole.

In [8]:
# Summarize the curated evidence by period and theme
pd.crosstab(evidence["period"], evidence["theme"])

theme,Sinai reenactment,age differentiation,age threshold,child learning,communal solidarity,counter-reception,covenant inclusion,covenant renewal,formation,inclusive hearing,minor obligation,reward to bringers,spiritual imprint,synagogue formation,translation as interpretation
period,,,,,,,,,,,,,,,
Biblical base,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
Early modern,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0
Early rabbinic,0,0,0,0,0,0,0,0,0,0,1,4,0,1,0
Hasidic,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
Late medieval,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
Medieval,1,0,0,1,0,0,0,0,1,1,0,1,0,0,0
Modern,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
Modern halakhic,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
Targumic,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

# 5 - Reception-history synthesis<a class="anchor" id="bullet5"></a>
##### [Back to ToC](#TOC)

The links in this section point to Sefaria locations represented in the evidence package. They open the text fragment used for the corresponding observation, rather than a general search page. Where the stored evidence is a passage range, the link may narrow that range to the particular verse under discussion.

## 5.1 - The rabbinic problem is not whether children are present<a class="anchor" id="bullet5x1"></a>
##### [Back to ToC](#TOC)

[Deuteronomy 31:10–13](https://www.sefaria.org/Deuteronomy.31.10-13) already commands their presence. The [early rabbinic
intervention](https://www.sefaria.org/Chagigah.3a.17) asks what *purpose* that presence serves when infants or very young children cannot perform the stated acts of learning. The answer places the reward on the adults who bring them.

## 5.2 - The saying in later interpretation<a class="anchor" id="bullet5x2"></a>
##### [Back to ToC](#TOC)

The [Bavli's three-part formula](https://www.sefaria.org/Chagigah.3a.17) also appears in [Targum Jonathan](https://www.sefaria.org/Targum_Jonathan_on_Deuteronomy.31.12), [Rashi](https://www.sefaria.org/Rashi_on_Deuteronomy.31.12), the [Mishneh Torah](https://www.sefaria.org/Mishneh_Torah%2C_Festival_Offering.3), the [Sefer HaChinukh](https://www.sefaria.org/Sefer_HaChinukh.612.1), and later commentary. It then supports arguments about women's Torah hearing, minors' ritual participation, parental duty, and the social meaning of public worship.

## 5.3 - Medieval interpreters reopen the scriptural rationale<a class="anchor" id="bullet5x3"></a>
##### [Back to ToC](#TOC)

[Ibn Ezra](https://www.sefaria.org/Ibn_Ezra_on_Deuteronomy.31.12.3) and especially [Abarbanel](https://www.sefaria.org/Abarbanel_on_Torah%2C_Deuteronomy.31.9.5) resist reducing children to passive occasions for adult reward. [Deuteronomy 31:13](https://www.sefaria.org/Deuteronomy.31.13) says that children who do not yet know will hear and learn. This raises a question: how does reward for the adults relate to the children's own hearing and learning?

## 5.4 - Later interpreters differentiate kinds of children<a class="anchor" id="bullet5x4"></a>
##### [Back to ToC](#TOC)

[Kli Yakar](https://www.sefaria.org/Kli_Yakar_on_Deuteronomy.31.12) and the [Minchat Chinukh](https://www.sefaria.org/Minchat_Chinukh.612.1.1) divide `טף` by developmental stage:
children capable of education can benefit directly, while younger children raise questions about the adult obligation to bring, the lower age boundary, and the meaning of reward.

## 5.5 - Synagogue reception produces extension and resistance<a class="anchor" id="bullet5x5"></a>
##### [Back to ToC](#TOC)

[Tractate Soferim](https://www.sefaria.org/Tractate_Soferim.18.6) turns Hakhel into precedent for bringing young girls to
synagogue. The [*Shenei Luchot HaBerit*](https://www.sefaria.org/Shenei_Luchot_HaBerit%2C_Aseret_HaDibrot%2C_Tamid%2C_Ner_Mitzva.130) preserves a counter-reading: if children disrupt prayer and desecrate the space, the bringer should expect punishment rather than reward.

## 5.6 - Hasidic readings of what children receive<a class="anchor" id="bullet5x6"></a>
##### [Back to ToC](#TOC)

[Sefat Emet](https://www.sefaria.org/Sefat_Emet%2C_Deuteronomy%2C_Vayeilech.3.2) argues that children can receive an inward illumination even without conceptual understanding. [Maor VaShemesh](https://www.sefaria.org/Maor_VaShemesh%2C_Vayeilech.5) places them within the love and unity of Israel that makes Torah hearing possible.

## 5.7 - Modern readings of covenant renewal<a class="anchor" id="bullet5x7"></a>
##### [Back to ToC](#TOC)

[A modern reading retained in the evidence package](https://www.sefaria.org/Covenant_and_Conversation%3B_Deuteronomy%3B_Renewal_of_the_Sinai_Covenant%2C_Vayeilech%2C_To_Renew_Our_Days.6) describes Hakhel as national covenant renewal and inclusive public education. The little ones signify that Torah belongs to the next generation before they can fully understand or consent to it.

# 6 - Main conclusion<a class="anchor" id="bullet6"></a>
##### [Back to ToC](#TOC)

The reception history supplies four recurring answers to why the little
ones come:

1. **adult merit** — bringing them is itself rewarded;
2. **formation** — repeated presence habituates future participants;
3. **direct reception** — children hear, learn, or receive a spiritual
   impression according to their capacity;
4. **corporate identity** — their presence makes the assembly visibly
   intergenerational and covenantal.

These answers coexist. The readings differ in how much they emphasise the adults who bring the children and the children who hear the Torah.

# 7 - Export reproducible results<a class="anchor" id="bullet7"></a>
##### [Back to ToC](#TOC)

We now save the search table, the links, and the full texts in this run’s folder. We also save the retrieval plan and the list of tools available from Sefaria. These files show what was requested and which service supplied the data.

In [9]:
# Export the retrieval tables and configuration for this run.
search_df.to_csv(RUN_DIR / "search_results.csv", index=False, encoding="utf-8-sig")
links_df.to_csv(RUN_DIR / "anchor_links.csv", index=False, encoding="utf-8-sig")
texts_df.to_csv(RUN_DIR / "full_texts.csv", index=False, encoding="utf-8-sig")
tools = await list_tools()
(RUN_DIR / "mcp_tool_inventory.json").write_text(json.dumps(tools, ensure_ascii=False, indent=2), encoding="utf-8")
(RUN_DIR / "retrieval_plan.json").write_text(json.dumps(strategy, ensure_ascii=False, indent=2), encoding="utf-8")
print("Run exported to", RUN_DIR)

Run exported to C:\Users\tonyj\AppData\Local\Temp\hakhel-mcp130-4wp8lnvi\Hakhel\reception_history\results\source_runs\live_2026-10-26_105712_58edc937

## 7.1 - Check the results<a class="anchor" id="bullet7x1"></a>
##### [Back to ToC](#TOC)

The final code cell makes the reading tables and checks the run. It keeps every search-term and reference relationship, while giving each full-text reference one row in the reading table. The discovery tags are simple keyword labels for finding passages; they are separate from the curated interpretation.

The audit lists missing curated references, failed text requests, and searches that reached the result limit. A search at the limit may have more matches than the tool returned. Check these entries before relying on the results.

In [10]:
# Build and validate the reading tables from this run alone.
def discovery_tags(row: pd.Series) -> str:
    """Assign navigation tags using the explicit keyword rules below."""
    haystack = " ".join(
        str(row.get(column, ""))
        for column in ["ref", "hebrew", "english", "raw_text"]
    )
    tags = []
    if any(term in haystack for term in ["Deuteronomy 31", "הקהל את העם", "האנשים והנשים והטף"]):
        tags.append("Torah instruction")
    if any(term in haystack for term in ["טף למה", "ליתן שכר", "bring them", "bringing them"]):
        tags.append("rabbinic reason for children")
    if any(term in haystack for term in ["חגיגה", "Chagigah"]):
        tags.append("Chagigah discussion")
    if any(term in haystack for term in ["קידושין", "Kiddushin", "time-bound"]):
        tags.append("mitzvah obligation discussion")
    return "; ".join(tags) or "related reference"



search_source_rows = pd.DataFrame([
    dict(row, source_run=RUN_ID)
    for item in raw_searches
    for row in result_rows(item["payload"], item["query"])
])
search_source_rows.to_csv(RUN_DIR / "search_sources.csv", index=False, encoding="utf-8-sig")
consolidated_search = search_source_rows.groupby("ref", as_index=False, sort=True).agg(
    source_runs=("source_run", "first"),
    search_queries=("search_query", lambda values: " | ".join(dict.fromkeys(values))),
)
consolidated_search.to_csv(RUN_DIR / "search_refs.csv", index=False, encoding="utf-8-sig")
full_text_source_rows = texts_df.assign(source_run=RUN_ID)
full_text_source_rows.to_csv(RUN_DIR / "text_sources.csv", index=False, encoding="utf-8-sig")
consolidated_texts = texts_df.drop_duplicates("ref").copy()
consolidated_texts["discovery_tags"] = consolidated_texts.apply(discovery_tags, axis=1)
consolidated_texts.to_csv(RUN_DIR / "texts.csv", index=False, encoding="utf-8-sig")

successful = consolidated_texts.fillna("")
successful = successful.loc[successful.get("hebrew", pd.Series("", index=successful.index)).ne("") | successful.get("english", pd.Series("", index=successful.index)).ne("")]
new_refs = set(successful["ref"])
audit = {
    "run_id": RUN_ID, "started_at": STARTED_AT,
    "completed_at": datetime.now(ZoneInfo("Europe/Amsterdam")).isoformat(),
    "started_at_utc": datetime.fromisoformat(STARTED_AT).astimezone(timezone.utc).isoformat(),
    "completed_at_utc": datetime.now(timezone.utc).isoformat(),
    "software_versions": {
        "python": sys.version.split()[0],
        **{name: package_metadata.version(name) for name in ("mcp", "pandas", "nbformat")},
    },
    "endpoint": MCP_SERVER_URL, "queries": len(SEARCH_QUERIES),
    "requested_texts": len(refs), "successful_texts": len(successful),
    "missing_curated_references": sorted(set(evidence["reference"]) - new_refs),
    "queries_at_result_limit": [item["query"] for item in raw_searches if len(result_rows(item["payload"], item["query"])) >= strategy["search_size"]],
    "retrieval_errors": json.loads(
        texts_df.loc[
            texts_df.get("error", pd.Series(index=texts_df.index, dtype=str)).notna()
        ].to_json(orient="records", force_ascii=False)
    ),
}
(RUN_DIR / "audit.json").write_text(json.dumps(audit, ensure_ascii=False, indent=2, allow_nan=False), encoding="utf-8")
display(pd.Series(audit))
print("Run exported. Review missing curated references, retrieval errors, and search limits in audit.json.")

run_id                                          live_2026-10-26_105712_58edc937
started_at                                     2026-10-26T10:57:12.506613+01:00
completed_at                                   2026-10-26T11:05:13.069540+01:00
started_at_utc                                 2026-10-26T09:57:12.506613+00:00
completed_at_utc                               2026-10-26T10:05:13.069562+00:00
software_versions             {'python': '3.14.2', 'mcp': '1.30.0', 'pandas'...
endpoint                                            https://mcp.sefaria.org/sse
queries                                                                      12
requested_texts                                                             345
successful_texts                                                            344
missing_curated_references                                                   []
queries_at_result_limit       [הקהל את העם האנשים והנשים והטף, ליתן שכר למבי...
retrieval_errors              [{'ref': 'German Commentary on Mishnah Kiddush...
dtype: object

Run exported. Review missing curated references, retrieval errors, and search limits in audit.json.

# 8 - Required libraries<a class="anchor" id="bullet8"></a>
##### [Back to ToC](#TOC)

Install the dependencies from [requirements.txt](requirements.txt) in the environment used by this notebook:

```powershell
python -m pip install -r requirements.txt
```

Run this command from the notebook directory. The [reproduction guide](../REPRODUCING.md) describes environment creation and kernel selection.

# 9 - Responsible disclosure<a class="anchor" id="bullet9"></a>
##### [Back to ToC](#TOC)

The author used OpenAI Codex to assist with Python code and data analysis. The author reviewed and edited the material and takes responsibility for the content and interpretation.

# 10 - Licences<a class="anchor" id="bullet10"></a>
##### [Back to ToC](#TOC)

The original code in this notebook is licensed under the [MIT License](../LICENSE).
The original research writing and explanatory text are licensed under [Creative Commons Attribution 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/).
Credit Tony Jurg, link the licence and repository, and indicate any changes when reusing the original text; see the [text licence](../LICENSE-TEXT.md).

Quoted source material, retrieved passages, and datasets retain their own terms.
See [Sources, attribution, and reuse](../DATA_RIGHTS.md) for their licences and attribution requirements.

# 11 - Notebook details<a class="anchor" id="bullet11"></a>
##### [Back to ToC](#TOC)

<div style="float: left;">
  <table>
    <tr><td><strong>Author</strong></td><td>Tony Jurg</td></tr>
    <tr><td><strong>Version</strong></td><td>1.7</td></tr>
    <tr><td><strong>Date</strong></td><td>October 26, 2026</td></tr>
  </table>
</div>